# Inageme name
# Updated manually

BOSS_ITEMS = {
    "Ancient Pickaxe",
    "Atlantean Worm Chest",
    "Atlantean Worm Figurine",
    "Atlantean Worm Heart",
    "Atlantean Worm Helmet",
    "Atlantean Worm Necklace",
    "Atlantean Worm Ring",
    "Atlantean Worm Sword",
    "Azeos Beak Necklace",
    "Azeos Figurine",
    "Azeos' Dash Feather",
    "Awakened Azeos Figurine",
    "Blue Leather Tome",
    "Blob Rosary Necklace",
    "Cipher Parchment",
    "Colossal Cicada Chest",
    "Core Commander Brigandine",
    "Core Commander Greaves",
    "Core Commander Helm",
    "Core Tech Chest",
    "Crydra Figurine",
    "Crydra's Ring",
    "Cryrdra Chest",
    "Druidra Chest",
    "Druidra Figurine",
    "Druidra's Ring",
    "Eostre Necklace",
    "Floating Titan's Chest",
    "Ghorm Chest",
    "Ghorm Figurine",
    "Ghorm's Horn",
    "Ghorm's Stomach Bag",
    "Giant Mitochondrion",
    "Glurch Chest",
    "Glurch Eye",
    "Glurch Figurine",
    "Golden Titan's Chest",
    "Haunted Hive Mother Chest",
    "Haunted Hive Mother Figurine",
    "Heart of the Hive Mother",
    "Hive Mother Chest",
    "Hive Mother Figurine",
    "Hivebone Breastplate",
    "Hivebone Helm",
    "Hivebone Pants",
    "Hydra Bone Breastplate",
    "Hydra Bone Helm",
    "Hydra Bone Shield",
    "Hydra Bone Shins",
    "Hydra Bone Sword",
    "Hydra Tooth",
    "Igneous Figurine",
    "Igenous' Chest",
    "Ivy Figurine",
    "Ivy's Chest",
    "Ivy's Pants",
    "Ivy's Ring",
    "Ivy's Thorn Hardness",
    "King Slime Crown",
    "King Slime Figurine",
    "King Slime's Chest",
    "Magma Horn Armor",
    "Magma Shin Armor",
    "Magma Torso Armor",
    "Malugaz Figurine",
    "Melting Crystal Ring",
    "Moonstone",
    "Morpha Figurine",
    "Morpha's Bubble Bag",
    "Morpha's Chest",
    "Morpha's Ring",
    "Oozy Slippery Egg",
    "Oracle Card, Entity",
    "Ostara Ring",
    "Omoroth Figurine",
    "Pile of Chum",
    "Pink Hydra Eye",
    "Pyrdra Chest",
    "Pyrdra Figurine",
    "Pyrdra's Necklace",
    "Ra-Akar Automaton",
    "Ra-Akar Figurine",
    "Ra-Akar's Necklace",
    "Radical Rabbit Ears",
    "Ring of Sand",
    "Ritual Dagger",
    "Ritual Goblet",
    "Royal Gel",
    "Samhain Curse Ring",
    "Samhain Offering Necklace",
    "Scarab Harness",
    "Scarab Legs",
    "Scarab Visor",
    "Scorching Aegis",
    "Sky Ring",
    "Slime Oil",
    "Slippery Slime Sword",
    "Soul of Omoroth",
    "Sulfossil Boots",
    "Sulfossil Cuirass",
    "Sulfossil Helmet",
    "Terarria - Journey's Beginning",
    "Titan's Chest",
    "Trinity Heart",
    "Urschleims Chest",
    "Void Gun",
    "Void Neuron",
    "White Hydra Eye"
}
