# Inageme name
# Updated manually

BOSS_ITEMS = {
"Blob Rosary Necklace",  
"Glurch Chest",  
"Glurch Eye",  
"Glurch Figurine",  
"Melting Crystal Ring",  
"Slime Oil",  
"Ghorm Chest",  
"Ghorm Figurine",  
"Ghorm's Horn",  
"Ghorm's Stomach Bag",  
"Heart of the Hive Mother",  
"Hive Mother Chest",  
"Hive Mother Figurine",   
"Ancient Pickaxe",  
"Azeos Beak Necklace",  
"Azeos' Dash Feather",  
"Azeos Figurine",  
"Pile of Chum",  
"Sky Ring",  
"Titan's Chest",  
"Floating Titan's Chest",  
"Omoroth Figurine",  
"Omoroth's Beak",  
"Omoroth's Chestplate",  
"Omoroth's Helm",  
"Omoroth's Leg Armor",  
"Omoroth's Necklace",  
"Omoroth's Ring",  
"Moonstone",  
"Soul of Omoroth",  
"Ra-Akar Figurine",  
"Ra-Akar's Necklace",  
"Ring of Sand",  
"Scarab Harness",  
"Scarab Legs",  
"Scarab Visor",  
"Ra-Akar Automaton",  
"Blue Leather Tome",  
"Malugaz Figurine",  
"Oracle Card, Entity",  
"Ritual Dagger",  
"Ritual Goblet",  
"Skull of Corrupted Shaman",  
"Skull Necklace",  
"Skull Ring",  
"Ivy Figurine",  
"Ivy's Chest",  
"Ivy's Pants",  
"Ivy's Ring",  
"Ivy's Thorn Hardness",  
"Druidra Figurine",  
"Druidra Chest",  
"Pink Hydra Eye",  
"Hydra Tooth",  
"Hydra Bone Shins",  
"Druidra's Ring",
"Sulfossil Helmet",
"Sulfossil Cuirass",
"Sulfossil Boots",
"Atlantean Worm Sword",  
"Atlantean Worm Ring",  
"Atlantean Worm Necklace",  
"Atlantean Worm Helmet",
"King Slime Crown",
"Hydra Bone Breastplate",
"Hydra Bone Helm",
"Hivebone Helm",
"Hivebone Breastplate",
"Hivebone Pants",
"Core Tech Chest",
"Void Gun",
"Trinity Heart",
"Core Commander Helm",
"Core Commander Brigandine",
"Core Commander Greaves",
}
