ITEMS = {
    "Admin Key",
    "Alchemy Table",
    "Ancient Hologram Pod",
    "Aquarium",
    "Arcane Potion",
    "Arrow Sign",
    "Atlantean Worm Scanner",
    "Automation Table",
    "Azeos the Sky Titan Scanner",
    "Bait Workbench",
    "Banner",
    "Basic Workbench",
    "Beach Terrarium",
    "Bed",
    "Black Paint Brush",
    "Blue Firework Rocket",
    "Blue Leather Tome",
    "Blue Paint Brush",
    "Blunder Bomb",
    "Boat",
    "Boat Workbench",
    "Bomb",
    "Bronze Breastplate",
    "Bronze Helm",
    "Bronze Pants",
    "Brown Paint Brush",
    "Bucket",
    "Bug Net",
    "Candle",
    "Candle Stack",
    "Carpenter's Table",
    "Cartography Table",
    "Cattle Transport Box",
    "Caveling Brute Plushie",
    "Cello",
    "Chaos Staff",
    "Charm Grenade",
    "Chef's Hat",
    "Chef's Jacket",
    "Chef's Pants",
    "Chest",
    "Chicken Pants",
    "Chicken Breast Piece",
    "Chicken Hat",
    "Conveyor Belt",
    "Cooking Pot",
    "Copper Anvil",
    "Copper Breastplate",
    "Copper Helm",
    "Copper Pants",
    "Copper Bar",
    "Copper Cross Necklace",
    "Copper Hoe",
    "Copper Key",
    "Copper Pickaxe",
    "Copper Shovel",
    "Copper Sword",
    "Copper Workbench",
    "Coral Amulet",
    "Coral Bridge",
    "Coral Door",
    "Coral Fence",
    "Coral Fence Gate",
    "Coral Floor",
    "Coral Wall",
    "Coral Wood Plank",
    "Core Keeper - Base Theme",
    "Corrupted Sap",
    "Cross Circuit",
    "Crude Bomb",
    "Crude Drill",
    "Crydra the Ice Titan Scanner",
    "Crystal Aquarium",
    "Crystal Meteor Chunk",
    "Crystal Terrarium",
    "CSD!3!? – It's Dangerous To Go Alone",
    "Cyan Paint Brush",
    "Daisy Flooring",
    "Decorated Winter Tree",
    "Decorative Pot",
    "Decorative Torch",
    "Delay Circuit",
    "Desert Terrarium",
    "Dresser",
    "Drill",
    "Druidra the Wild Titan Scanner",
    "Drumkit",
    "Dynamite Pack",
    "Easter Egg Flowerpot",
    "Easter Egg Lamp",
    "Easter Garland",
    "Easter Meadow Stool",
    "Easter Meadow Table",
    "Easter Pedestal",
    "Easter Pillar",
    "Eerie Dresser",
    "Eerie Floor",
    "Eerie Rug",
    "Eerie Stool",
    "Eerie Table",
    "Eerie Wall",
    "Egg Incubator",
    "Eggcellent Pants",
    "Eggcellent Breast Piece",
    "Eggcellent Hat",
    "Electrical Door",
    "Electrical Wire",
    "Electricity Generator",
    "Electricity Stick",
    "Electronics Table",
    "Enrage Potion",
    "Expert Lure",
    "Explorer Backpack",
    "Explorer's Hat",
    "Explorer's Jacket",
    "Explorer's Pants",
    "Explosives Deposit",
    "Feeding Tray",
    "Festive Fireplace",
    "Festive Stool",
    "Festive Table",
    "Festive Wall Lights",
    "Fire Grenade",
    "Floor Pillow",
    "Flower Crown",
    "Flute",
    "Furnace",
    "Fury Forge",
    "Galaxite Anvil",
    "Galaxite Torso",
    "Galaxite Helm",
    "Galaxite Pants",
    "Galaxite Bar",
    "Galaxite Bridge",
    "Galaxite Chakram",
    "Galaxite Dagger",
    "Galaxite Door",
    "Galaxite Fence",
    "Galaxite Fence Gate",
    "Galaxite Fishing Rod",
    "Galaxite Floor",
    "Galaxite Key",
    "Galaxite Pickaxe",
    "Galaxite Shovel",
    "Galaxite Sword",
    "Galaxite Trap",
    "Galaxite Turret",
    "Galaxite Wall",
    "Galaxite Workbench",
    "Ghorm the Devourer Scanner",
    "Glass Bridge",
    "Glass Floor",
    "Glass Piece",
    "Glass Smelter",
    "Glass Wall",
    "Glass Workbench",
    "Gleam Wood Bridge",
    "Gleam Wood Door",
    "Gleam Wood Fence",
    "Gleam Wood Fence Gate",
    "Gleam Wood Floor",
    "Gleam Wood Plank",
    "Gleam Wood Wall",
    "Glow Tulip Ring",
    "Glowing Bait",
    "Go-Kart Workbench",
    "Gold Bar",
    "Gold Crystal Necklace",
    "Gold Crystal Ring",
    "Golden Spike Ring",
    "Greater Healing Potion",
    "Green Firework Rocket",
    "Green Paint Brush",
    "Grenade",
    "Grey Paint Brush",
    "Grimy Stone Floor",
    "Grimy Stone Pillar",
    "Grubzooka",
    "Guardian's Potion",
    "Harp",
    "Healing Potion",
    "Heart Painting",
    "Heart-shaped Rug",
    "Hive Mother Scanner",
    "Hydra Altar",
    "Igneous the Molten Mass Scanner",
    "Iron Anvil",
        "Iron Breastplate",
    "Iron Helm",
    "Iron Pants",
    "Iron Bar",
    "Iron Bow",
    "Iron Chunk Necklace",
    "Iron Fishing Rod",
    "Iron Halberd",
    "Iron Hoe",
    "Iron Key",
    "Iron Pickaxe",
    "Iron Shield",
    "Iron Shovel",
    "Iron Sword",
    "Iron Workbench",
    "Ivy the Poisonous Mass Scanner",
    "Jewelry Workbench",
    "Keen Potion",
    "Key Casting Table",
    "Laboratory Table",
    "Lamp",
    "Large Bomb",
    "Large Shiny Glimmering Object",
    "Large Watering Can",
    "Larva Spike Club",
    "Leash",
    "Lever",
    "Lit Floor",
    "Livestock Workbench",
    "Logic Circuit",
    "Loom",
    "Loose Flooring",
    "Luxury Winter Present",
    "Magic Mirror",
    "Magma Slime",
    "Magnetic Ring",
    "Malugaz Summoning Idol",
    "Malugaz the Corrupted Scanner",
    "Mannequin",
    "Medium Fish Pouch",
    "Medium Ore and Block Pouch",
    "Medium Seed and Crop Pouch",
    "Medium Valuable Pouch",
    "Minecart",
    "Morpha the Aquatic Mass Scanner",
    "Mouse Bomb",
    "Music Sheet Stand",
    "Music Workbench",
    "Nimruza, Queen of the Burrowed Sands Scanner",
    "Octarine Anvil",
    "Octarine Breastplate",
    "Octarine Helm",
    "Octarine Pants",
    "Octarine Axe",
    "Octarine Backpack",
    "Octarine Bar",
    "Octarine Bow",
    "Octarine Fishing Rod",
    "Octarine Garden Trowel",
    "Octarine Key",
    "Octarine Necklace",
    "Octarine Pickaxe",
    "Octarine Ring",
    "Octarine Shield",
    "Octarine Shovel",
    "Octarine Sword",
    "Octarine Workbench",
    "Omoroth the Sea Titan Scanner",
    "Oracle Deck",
    "Orange Paint Brush",
    "Orb Lantern",
    "Owlboy - Main Title",
    "Pact of Power Potion",
    "Paintable Festive Wall Lights",
    "Paintable Floor",
    "Paintable Wall",
    "Painter's Table",
    "Painting",
    "Pandorium Helm"
    "Pandorium Pants"
    "Pandorium Chestplate and Bracers"
    "Pandorium Axe",
    "Pandorium Bar",
    "Passage Aquarium",
    "Passage Terrarium",
    "Peach Paint Brush",
    "Pearl Lantern",
    "Pedestal",
    "Phantom Spark",
    "Pink Cherry Tree",
    "Pink Paint Brush",
    "Plank",
    "Pocket Piano",
    "Poison Aid Potion",
    "Poison Grenade",
    "Poison Slime",
    "Portal",
    "Pressure Plate",
    "Primeval Slime Cell",
    "Primitive Go-kart",
    "Proficient Jewelry Workbench",
    "Proximity Bomb",
    "Purple Firework Rocket",
    "Purple Paint Brush",
    "Pyrdra the Fire Titan Scanner",
    "Ra-Akar the Sand Titan Scanner",
    "Rail",
    "Railway Forge",
    "Rain Coat",
    "Rubber Boots",
    "Recall Idol",
    "Red Firework Rocket",
    "Red Paint Brush",
    "Renegade Go-kart",
    "Ritual Dagger",
    "Robot Arm",
    "Rocky Aquarium",
    "Roofing Gadget",
    "Rug",
    "Rune Song",
    "Salvage and Repair Station",
    "Scarlet Anvil",
        "Scarlet Helm",
    "Scarlet Breastplate",
    "Scarlet Pants",
    "Scarlet Bar",
    "Scarlet Bridge",
    "Scarlet Chunk Necklace",
    "Scarlet Crossbow",
    "Scarlet Dagger",
    "Scarlet Door",
    "Scarlet Fence",
    "Scarlet Fence Gate",
    "Scarlet Fishing Rod",
    "Scarlet Floor",
    "Scarlet Hoe",
    "Scarlet Key",
    "Scarlet Pickaxe",
    "Scarlet Shell Backpack",
    "Scarlet Shovel",
    "Scarlet Sword",
    "Scarlet Wall",
    "Scarlet Workbench",
    "Seasonal Calendar",
    "Sign",
    "Slime",
    "Slime Sword",
    "Slingshot",
    "Slippery Slime",
    "Small Backpack",
    "Small Fish Pouch",
    "Small Lantern",
    "Small Ore and Block Pouch",
    "Small Seed and Crop Pouch",
    "Small Valuable Pouch",
    "Smelter Kiln",
    "Snow Block",
    "Snowball Pyramid",
    "Snowman",
    "Solarite Anvil",
    "Solarite Barbute",
    "Solarite Cuirass",
    "Solarite Tassets",
    "Solarite Bar",
    "Solarite Crossbow",
    "Solarite Fishing Rod",
    "Solarite Key",
    "Solarite Pickaxe",
    "Solarite Sword",
    "Solarite Workbench",
    "Soul Seeker",
    "Speeder",
    "Speeder Go-kart",
    "Spicy Bait",
    "Spike Trap",
    "Sprinkler",
    "Sticky Bait",
    "Stone Bricks Wall",
    "Stone Bridge",
    "Stone Door",
    "Stone Fence",
    "Stone Fence Gate",
    "Stone Floor",
    "Stone Lantern",
    "Stoneskin Potion",
    "Stormbringer",
    "Straw-bale Wall",
    "Stun Grenade",
    "Top Hat",
    "Suit Jacket",
    "Suit Pants",
    "Sulfur Bomb",
    "Sunken Aquarium",
    "Sweet Bait",
    "Swift Ring",
    "Table Saw",
    "Tapestry",
    "Teal Paint Brush",
    "Terrarium",
    "The BIG",
    "Thin Glass Wall",
    "Thumper",
    "Tin Anvil",
    "Tin pants",
    "Tin helm",
    "Tin breastplate",
    "Tin Axe",
    "Tin Bar",
    "Tin Dagger",
    "Tin Fishing Rod",
    "Tin Hoe",
    "Tin Pickaxe",
    "Tin Shovel",
    "Tin Sword",
    "Tin Workbench",
    "Torch",
    "Twisted Roots Torch",
    "Upgrade Station",
    "Urschleim Scanner",
    "Valentine's Candles",
    "Void Bomb",
    "Wall Hearts",
    "Wash Basin",
    "Watering Can",
    "Wedding Dress",
    "White Cherry Tree",
    "White Paint Brush",
    "Wilderness Aquarium",
    "Wilderness Terrarium",
    "Wind Organ of Fire",
    "Wind Organ of Ice",
    "Wind Organ of Wilderness",
    "Winter Present",
    "Wonky Minecart",
    "Wood Chest",
    "Wood Helm",
    "Wood Pants",
    "Wood Bow",
    "Wood Bridge",
    "Wood Door",
    "Wood Fence",
    "Wood Fence Gate",
    "Wood Fishing Rod",
    "Wood Floor"
}