# Inageme name
# Updated manually

CRAFTABLE_ITEMS = {
    "Scarlet Helm",
    "Scarlet Breastplate",
    "Scarlet Pants",
    "Wood Chest",
    "Wood Helm",
    "Wood Pants",
    "Chef's Hat",
    "Chef's Jacket",
    "Chef's Pants",
    "Copper Breastplate",
    "Copper Helm",
    "Copper Pants",
    "Wedding Dress",
    "Top Hat",
    "Suit Jacket",
    "Suit Pants",
    "Iron Breastplate",
    "Iron Helm",
    "Iron Pants",
    "Octarine Breastplate",
    "Octarine Helm",
    "Octarine Pants",
    "Bronze Breastplate",
    "Bronze Helm",
    "Bronze Pants",
    "Galaxite Breast Armor",
    "Galaxite Helm",
    "Galaxite Pants",
    "Flower Crown",
    "Explorer's Hat",
    "Explorer's Jacket",
    "Explorer's Pants",
}
