# Inageme name
# Updated manually

DIGSPOT_ITEMS = {
"Adventurer's Hat",
"Amber Chunk",
"Ammonite",
"Balloon Spore",
"Black Bubble Pearl",
"Black Necklace",
"Black Ring",
"Bomb",
"Bomb Pepper Seed",
"Bone Creole",
"Broken Core Idol",
"Bubble Pearl",
"Charred Caveling Skull",
"Coral Wood",
"Crescent Ring",
"Fish Fossil",
"Flame Ring",
"Fizzy Crystal",
"Forked Coral",
"Galaxite Key",
"Galaxite Ore",
"Geode",
"Glow Tulip Seed",
"Gold Bar",
"Hard Thorn",
"Heart Berry Necklace",
"Heart Berry Seed",
"Loyal Egg",
"Large Bomb",
"Mechanical Part",
"Mercenary Headband",
"Mercenary Pants",
"Mercenary Tank Top",
"Miner's Labour Suit",
"Miner's Worker Pants",
"Octarine Ore",
"Ocarina",
"Old Amulet",
"Old Spore Mask",
"Peasant Chest",
"Peasant Hat",
"Petrified Coral",
"Petrified Trilobite",
"Pickaxe Head",
"Recall Idol",
"Root Seed",
"Rusty Dagger",
"Small Valuable Pouch",
"Stone Cap",
"Tome of the Deep",
"Triangle Trinket",
"Twisted Agate",
"Wildwarden Pants",
"Worker Handcuff"
}
