# Inageme name
# Updated manually

DIGSPOT_ITEMS = {
"Heart Berry Seed",
"Bomb Pepper Seed",
"Glow Tulip Seed",
"Root Seed",
"Geode",
"Old Amulet",
"Bone Creole",
"Twisted Agate",
"Triangle Trinket",
"Ammonite",
"Broken Core Idol",
"Peasant Hat",
"Peasant Chest",
"Heart Berry Necklace",
"Loyal Egg",
"Adventurer's Hat",
"Rusty Dagger",
"Crescent Ring",
"Small Valuable Pouch",
"Old Spore Mask",
"Hard Thorn",
"Balloon Spore",
"Amber Chunk",
"Petrified Coral",
"Stone Cap",
"Ocarina",
"Mercenary Headband",
"Mercenary Pants",
"Mercenary Tank Top",
"Bomb",
"Coral Wood",
"Octarine Ore",
"Fish Fossil",
"Petrified Trilobite",
"Forked Coral",
"Gold Bar",
"Fizzy Crystal",
"Bubble Pearl",
"Black Bubble Pearl",
"Wildwarden Pants",
"Large Bomb",
"Tome of the Deep",
"Mechanical Part",
"Galaxite Ore",
"Charred Caveling Skull",
"Worker Handcuff",
"Pickaxe Head",
"Black Necklace",
"Flame Ring",
"Black Ring",
"Miner's Labour Suit",
"Miner's Worker Pants",
"Recall Idol",
"Galaxite Key"
}
