# Inageme name
# Updated manually

DROP_ITEMS = {
    "Apprentice Hat",
    "Apprentice Pants",
    "Apprentice Robe",
    "Arcane Monk Blindfold",
    "Arcane Monk Cloak",
    "Arcane Monk Leggings",
    "Assassin Cloak",
    "Assassin Hood",
    "Blast Helmet",
    "Blast Pants",
    "Blast Plackart",
    "Carapace Breastplate",
    "Carapace Helm",
    "Caveling Chest",
    "Caveling Hood",
    "Caveling Pants",
    "Chieftain Headdress",
    "Chieftain Shorts",
    "Chieftain Tunic",
    "Corrupt Warden Mask",
    "Corrupt Warden Shorts",
    "Corrupt Warden Tunic",
    "Cosmos Legwear",
    "Cosmos Torso",
    "Cosmos Visor Helm",
    "Desert Guardian Mask",
    "Desert Guardian Pants",
    "Desert Guardian Tunic",
    "Mercenary Headband",
    "Mercenary Pants",
    "Mercenary Tank Top",
    "Paladin Harness",
    "Paladin Mask",
    "Paladin Pants",
}
