itemfishspot_data = {
    "stoneFishingLoot": [
        "Grey Kelp",
        "Scrap Parts",
        "Iron Ore",
        "Fiber",
        "Gold Ore",
        "Soft Sponge",
        "Adder Stone",
        "Caveling Perfume",
        "Bubble Pearl Necklace",
        "Goldfish Ring",
        "Enhydro Crystal",
        "Iron Key",
        "Locked Iron Chest",
        "Trenchcoat",
        "Deceased Explorer",
        "Large Bomb"
    ],
    
    "natureFishingLoot": [
        "Red Kelp",
        "Scrap Parts",
        "Scarlet Ore",
        "Fiber",
        "Gold Ore",
        "Lost Paddle",
        "Feather Fish Scale",
        "Caveling Medal",
        "Rainbow Kelp",
        "Sea Foam Ring",
        "Scarlet Key",
        "Locked Scarlet Chest",
        "Trenchcoat",
        "Mercenary Headband",
        "Mercenary Pants",
        "Mercenary Tank Top",
        "Scarlet Hand Drill",
        "Lily Pad Hat",
        "Lily Pad Tunic",
        "Lily Pad Shorts"
    ],
    
    "moldFishingLoot": [
        "Pale Kelp",
        "Scrap Parts",
        "Scarlet Ore",
        "Fiber",
        "Gold Ore",
        "Giant Germ",
        "Mold Shell",
        "Ceremonial Flute",
        "Data Slate",
        "Kelp Mantle",
        "Scarlet Key",
        "Locked Scarlet Chest",
        "Plague Mask"
    ],
    
    "seaFishingLoot": [
        "Blue Kelp",
        "Scrap Parts",
        "Octarine Ore",
        "Fiber",
        "Gold Ore",
        "Giant Squid Eye",
        "Golden Needle",
        "Polished Shell",
        "Opabinia Fossil",
        "Golden Jellyfish",
        "Diving Helm",
        "Octarine Key",
        "Locked Octarine Chest",
        "Octarine Sledge Hammer",
        "Wildwarden Pants",
        "Pearl Lantern",
        "Crescent Necklace",
        "Large Fish Pouch"
    ],
    
    "desertFishingLoot": [
        "Flesh Kelp",
        "Galaxite Ore",
        "Scrap Parts",
        "Fiber",
        "Gold Ore",
        "Ancient Fishing Hook",
        "Broken Gourd",
        "Broken Toy Ship",
        "Kingfish Scale",
        "Noble Ring",
        "Double Ring",
        "Oracle Card Temperance",
        "Galaxite Key",
        "Locked Galaxite Chest",
        "Puppet Ring",
        "Desert Guardian Mask",
        "Desert Guardian Tunic",
        "Paladin Pants",
        "Large Fish Pouch"
    ],
    
    "lavaFishingLoot": [
        "Dark Blue Kelp",
        "Scrap Parts",
        "Galaxite Ore",
        "Gold Ore",
        "Ancient Gemstone",
        "Ancient Fishing Hook",
        "Fusion Alloy",
        "Starlight Shards",
        "Miner's Protective Helm",
        "Fusioned Chunk Necklace",
        "Core Iris",
        "Galaxite Key",
        "Locked Galaxite Chest"
    ],
    
    "crystalFishingLoot": [
        "Crystal Kelp",
        "Scrap Parts",
        "Solarite Ore",
        "Gold Ore",
        "Crystal Bone",
        "Triops Fossil",
        "Catalyst Gemstone",
        "Gleam Wood Seed",
        "Sunrice Seed",
        "Lunacorn Seed",
        "Solarite Key",
        "Ninja Cowl",
        "Ninja Garments",
        "Ninja Leggings"
    ],
    
    "passageFishingLoot": [
        "Sulfur Bud",
        "Triops Fossil",
        "Lost Paddle",
        "Gold Ore",
        "Pandorium Ore"
    ],
    
    "dirtFishingLoot": [
        "Green Kelp",
        "Scrap Parts",
        "Copper Ore",
        "Fiber",
        "Wood",
        "Rusty Spoon",
        "Amber Fish Egg",
        "Cave Guppy Necklace",
        "Scuba Fins",
        "Golden Starfish",
        "Copper Key",
        "Locked Copper Chest",
        "Crude Bomb",
        "Small Fish Pouch"
    ],
    
    "larvaFishingLoot": [
        "Yellow Kelp",
        "Scrap Parts",
        "Tin Ore",
        "Fiber",
        "Wood",
        "Mucus Amoeba",
        "Parasite Fossil",
        "Rusted Ring",
        "Neptune Necklace",
        "Golden Cocoon",
        "Grub Pearl",
        "Iron Key",
        "Locked Iron Chest",
        "Wildwarden Necklace",
        "Bomb"
    ]
}