# https://core-keeper.fandom.com/wiki/Category:Items_by_base_level
items_by_base_level = {
    1: [
        "Peasant armor",
        "Peasant Chest",
        "Peasant Hat",
        "Wood Pickaxe",
        "Wood Shovel",
        "Wooden Sword"
        ],
    2: [
        "Blue Cave Guppy",
        "Copper Cross Necklace",
        "Copper Pickaxe",
        "Copper Shovel",
        "Copper Sledge Hammer",
        "Copper Sword",
        "Miner Backpack",
        "Orange Cave Guppy",
        "Simple Staff",
        "Small Backpack",
        "Small Lantern",
        "Tome of the Dark",
        "Wood armor",
        "Wood Bow",
        "Wood Chest",
        "Wood Crossbow",
        "Wood Fishing Rod",
        "Wood Helm",
        "Wood Pants",
        "Wooden Shield"
    ],
    3: [
        "Adventurer's Hat",
        "Apprentice armor",
        "Apprentice Hat",
        "Apprentice Pants",
        "Apprentice Robe",
        "Cave Guppy Necklace",
        "Copper armor",
        "Copper Breastplate",
        "Copper Helm",
        "Copper Pants",
        "Festive Hat",
        "Rain armor",
        "Rain Coat",
        "Ranger armor",
        "Ranger Hood",
        "Ranger Pants",
        "Ranger Tunic",
        "Ring of Stone",
        "Rock Jaw",
        "Rubber Boots",
        "Rusty Dagger",
        "Shrooman Cap",
        "Small Fish Pouch",
        "Small Ore and Block Pouch",
        "Small Seed and Crop Pouch",
        "Small Valuable Pouch",
        "Snowman Hat",
        "Witch Doctor armor",
        "Witch Doctor Hat",
        "Witch Doctor Jeans",
        "Witch Doctor Vest"
    ],
    4: [
        "Gem Crab",
        "Glowing Bait",
        "Green Blister Head",
        "Hand Drill",
        "Medium Fish Pouch",
        "Medium Ore and Block Pouch",
        "Medium Seed and Crop Pouch",
        "Medium Valuable Pouch",
        "Scuba Fins",
        "Snowball",
        "Spicy Bait",
        "Sticky Bait",
        "Sticky Stick",
        "Stun Grenade",
        "Sweet Bait",
        "Swift Feather",
        "Tin armor",
        "Tin breastplate",
        "Tin Fishing Rod",
        "Tin helm",
        "Tin pants",
        "Tin Pickaxe",
        "Tin Shovel",
        "Tin Sledge Hammer",
        "Yellow Blister Head"
    ],
    5: [
        "Blob Rosary Necklace",
        "Bronze armor",
        "Bronze Breastplate",
        "Bronze Helm",
        "Bronze Pants",
        "Chieftain armor",
        "Chieftain Headdress",
        "Chieftain Shorts",
        "Chieftain Tunic",
        "Crescent Ring",
        "Cupid Bow",
        "Cupid Tunic",
        "Devil Worm",
        "Explorer Backpack",
        "Fang Necklace",
        "Flintlock Musket",
        "Glow Tulip Ring",
        "Heart Berry Necklace",
        "Hunting Spear",
        "Large Fish Pouch",
        "Large Ore and Block Pouch",
        "Large Seed and Crop Pouch",
        "Large Valuable Pouch",
        "Melting Crystal Ring",
        "Pot armor",
        "Pot Lid",
        "Pot Tub",
        "Rusted Ring",
        "Slingshot",
        "Tin Axe",
        "Tin Dagger",
        "Tin Sword",
        "Valentine Necklace",
        "Valentine Ring"
    ],
    6: [
        "Clot Ring",
        "Cooking Pot armor",
        "Cooking Pot Lid",
        "Cooking Pot Tub",
        "Dagger Fin",
        "Dracularva Cape",
        "Iron Fishing Rod",
        "Iron Pickaxe",
        "Iron Shovel",
        "Iron Sledge Hammer",
        "Lantern",
        "Skirmisher Cap",
        "Slime Sword",
        "Swift Ring"
    ],
    7: [
        "Battle Axe",
        "Blast armor",
        "Blast Helmet",
        "Blast Pants",
        "Blast Plackart",
        "Boundary Ring",
        "Caveling armor",
        "Caveling Chest",
        "Caveling Hood",
        "Caveling Pants",
        "Gold Crystal Ring",
        "Hourglass Ring",
        "Iron armor",
        "Iron Bow",
        "Iron Breastplate",
        "Iron Chunk Necklace",
        "Iron Halberd",
        "Iron Helm",
        "Iron Pants",
        "Iron Shield",
        "Iron Sword",
        "Larva Ring",
        "Makeshift Goggles",
        "Pink Palace Fish",
        "Pumpkin Lantern",
        "Quill Rifle",
        "Researcher's armor",
        "Researcher's Coat",
        "Researcher's Pants",
        "Soaring armor",
        "Soaring Headgear",
        "Soaring Pants",
        "Soaring Poncho",
        "Spooky Blanket armor",
        "Spooky Blanket Cape",
        "Spooky Blanket Hood",
        "Stone armor",
        "Stone Chestplate",
        "Stone Pants",
        "Teal Palace Fish",
        "Tome of Ashes",
        "Trenchcoat"
    ],
    8: [
        "Ammonite Necklace",
        "Arcane Staff",
        "Azure Feather Fish",
        "Bubble Pearl Necklace",
        "Carapace armor",
        "Carapace Breastplate",
        "Carapace Helm",
        "Emerald Feather Fish",
        "Fireball Staff",
        "Frankenbrute Head",
        "Ghorm's Stomach Backpack",
        "Gingerbread armor",
        "Gingerbread Hood",
        "Gingerbread Pants",
        "Gingerbread Top",
        "Gingerbreadman Head",
        "Gold Crystal Necklace",
        "Goldfish Ring",
        "Grub Egg Necklace",
        "Hand Mortar",
        "Larva armor",
        "Larva Chest",
        "Larva Helm",
        "Larva Spike Club",
        "Neptune Necklace",
        "Pipe Club",
        "Pumpkin Head",
        "Rift Lens",
        "Ring of Rock",
        "Samhain Curse Ring",
        "Samhain Offering Necklace"
    ],
    9: [],
    10: [
        "Astral Jelly",
        "Azeos' Dash Feather",
        "Blowpipe",
        "Blue Bikini Bottom",
        "Blue Bikini Top",
        "Blue Board Shorts",
        "Bottom Tracer",
        "Broken Handle",
        "Caveling Mother's Ring",
        "Corrupt Warden armor",
        "Corrupt Warden Mask",
        "Corrupt Warden Shorts",
        "Corrupt Warden Tunic",
        "Crescent Necklace",
        "Eostre Necklace",
        "Green Bikini Bottom",
        "Green Bikini Top",
        "Green Board Shorts",
        "Hunter armor",
        "Hunter Cloak",
        "Hunter Hood",
        "Ivy's Ring",
        "Kelp Mantle",
        "Lily Pad armor",
        "Lily Pad Hat",
        "Lily Pad Shorts",
        "Lily Pad Tunic",
        "Mercenary armor",
        "Mercenary Headband",
        "Mercenary Pants",
        "Mercenary Tank Top",
        "Moldweb armor",
        "Moldweb Breastplate",
        "Moldweb Helm",
        "Moldweb Pants",
        "Ostara Ring",
        "Petal Ring",
        "Puppet Ring",
        "Purple Bait",
        "Radical Rabbit Ears",
        "Radical Rabbit Headband",
        "Red Bikini Bottom",
        "Red Bikini Top",
        "Red Board Shorts",
        "Rot Fish",
        "Rusted Necklace",
        "Scarlet armor",
        "Scarlet Breastplate",
        "Scarlet Helm",
        "Scarlet Pants",
        "Scarlet Shell Backpack",
        "Sunglasses",
        "Tome of Sprouts",
        "Towel",
        "Toxic Defender",
        "Wildwarden armor",
        "Wildwarden Mask",
        "Wildwarden Necklace",
        "Wildwarden Pants",
        "Wildwarden Pauldrons",
        "Wildwarden Ring",
        "Wooden Ring",
        "Wooden Thorn Ring"
    ],
    11: [
        "Ancient Gem Necklace",
        "Ancient Guardian Necklace",
        "Ancient Pickaxe",
        "Azeos Beak Necklace",
        "Black Steel Urchin",
        "Coral Amulet",
        "Golden Dart",
        "Golden Spike Ring",
        "Ivy's armor",
        "Ivy's Pants",
        "Ivy's Thorn Harness",
        "Magnetic Ring",
        "Mold Ring",
        "Mold Vein Necklace",
        "Octarine Shovel",
        "Remedaisy Necklace",
        "Scarlet Chunk Necklace",
        "Silver Dart",
        "Sky Ring",
        "Tentacle Whip",
        "Tome of the Dead",
        "Topaz Ring",
        "Vicious Ring",
        "White Glass Ring"
    ],
    12: [
        "Ancient Guardian Ring",
        "Bubble Gun",
        "Caveling ID",
        "Golden Jellyfish",
        "Lucky Ring",
        "Morpha's Bubble Bag",
        "Octarine armor",
        "Octarine Axe",
        "Octarine Backpack",
        "Octarine Bow",
        "Octarine Breastplate",
        "Octarine Fishing Rod",
        "Octarine Helm",
        "Octarine Necklace",
        "Octarine Pants",
        "Octarine Pickaxe",
        "Octarine Ring",
        "Octarine Shield",
        "Octarine Sledge Hammer",
        "Octarine Sword",
        "Pearl Lantern",
        "Pink Coralotl",
        "Plague Mask",
        "Poisonous Sickle",
        "Sandy Spikeback",
        "Septum Ring",
        "Slime Armor",
        "Slime Helm",
        "Solid Spikeback",
        "Soul Lantern",
        "Tome of the Deep",
        "Torc Necklace",
        "White Coralotl"
    ],
    13: [
        "Anchor Axe",
        "Ancient Gem Ring",
        "Bone Necklace",
        "Bone Ring",
        "Charm Grenade",
        "Concealed Blade",
        "Conch Shell Necklace",
        "Coral Ring",
        "Diving Helm",
        "Expert Lure",
        "Fire Grenade",
        "Morpha's Ring",
        "Noble Ring",
        "Oceanheart Necklace",
        "Omoroth's armor",
        "Omoroth's Chestplate",
        "Omoroth's Helm",
        "Omoroth's Leg Armor",
        "Omoroth's Necklace",
        "Omoroth's Ring",
        "Paladin armor",
        "Paladin Harness",
        "Paladin Mask",
        "Paladin Pants",
        "Poison Grenade",
        "Polished Copper Cross Necklace",
        "Polished Coral Amulet",
        "Polished Glow Tulip Ring",
        "Polished Gold Crystal Necklace",
        "Polished Gold Crystal Ring",
        "Polished Golden Spike Ring",
        "Polished Iron Chunk Necklace",
        "Polished Magnetic Ring",
        "Polished Octarine Necklace",
        "Polished Octarine Ring",
        "Polished Scarlet Chunk Necklace",
        "Polished Swift Ring",
        "Rune Song",
        "Scholar's armor",
        "Scholar's Cloak",
        "Scholar's Hood",
        "Scholar's Staff",
        "Sentry Shield",
        "Slippery Slime Sword",
        "Sorcerer armor",
        "Sorcerer Hood",
        "Sorcerer Pants",
        "Sorcerer Robe",
        "Spine Ring",
        "Sun Caller",
        "Turtle Shell"
    ],
    14: [
        "Assassin armor",
        "Assassin Cloak",
        "Assassin Hood",
        "Black Necklace",
        "Bomb Scarab Mortar",
        "Bright Lava Eater",
        "Brown Dune Tail",
        "Dark Lava Eater",
        "Double Ring",
        "Flame Ring",
        "Galaxite armor",
        "Galaxite Chakram",
        "Galaxite Dagger",
        "Galaxite Fishing Rod",
        "Galaxite Helm",
        "Galaxite Pants",
        "Galaxite Pickaxe",
        "Galaxite Shovel",
        "Galaxite Sledge Hammer",
        "Galaxite Sword",
        "Galaxite Torso",
        "Grey Dune Tail",
        "Moonstone",
        "Nomad Necklace",
        "Nomad Ring",
        "Omoroth's Beak",
        "Sentry Helm",
        "Tassel armor",
        "Tassel Earrings",
        "Tassel Skirt",
        "Tassel Top",
        "Throwing Daggers",
        "Zealot's Scimitar"
    ],
    15: [
        "Beryll Angle Fish",
        "Black Ring",
        "Bomb Ring",
        "Crystal Meteor Chunk",
        "Elder Dragonfish",
        "Flame Necklace",
        "Fusioned Chunk Necklace",
        "Lava Battle Axe",
        "Miner's armor",
        "Miner's Labour Suit",
        "Miner's Worker Pants",
        "Oracle Deck",
        "Phantom Spark",
        "Prehistoric Crystal Spear",
        "Ra-Akar's Necklace",
        "Ring of Sand",
        "Scarab armor",
        "Scarab Harness",
        "Scarab Legs",
        "Scarab Visor",
        "Smithing Glove",
        "Tornis Kingfish",
        "Verdant Dragonfish"
    ],
    16: [
        "Burnzooka",
        "Core Iris",
        "Cosmos armor",
        "Cosmos Legwear",
        "Cosmos Torso",
        "Cosmos Visor Helm",
        "Crydra's Ring",
        "Crystal Shard Club",
        "Druidra's Ring",
        "Gemstone armor",
        "Gemstone Garment",
        "Gemstone Harem Pants",
        "Glass Bead Ring",
        "Glistening Deepstalker",
        "Godsent King armor",
        "Godsent King Breast Armor",
        "Godsent King Mask",
        "Godsent King Pants Armor",
        "Grim armor",
        "Grim Breastplate",
        "Grim Hood",
        "Grim Legwear",
        "Hazmat armor",
        "Hazmat Helm",
        "Hazmat Suit Jacket",
        "Hazmat Suit Pants",
        "Hydra Bone Shield",
        "Hydra Bone Sword",
        "Hydra Tooth",
        "Jasper Angle Fish",
        "Litho Trilobite",
        "Magma armor",
        "Magma Horn Armor",
        "Magma Shin Armor",
        "Magma Torso Armor",
        "Miner's Protective Helm",
        "Pet Rock",
        "Pyrdra's Necklace",
        "Ricochet Shuriken",
        "Scholar Backpack",
        "Scorching Aegis",
        "Solarite armor",
        "Solarite Barbute",
        "Solarite Crossbow",
        "Solarite Cuirass",
        "Solarite Fishing Rod",
        "Solarite Pickaxe",
        "Solarite Sword",
        "Solarite Tassets",
        "Soul Seeker",
        "Terra Trilobite"
    ],
    17: [
        "Arcane Monk armor",
        "Arcane Monk Blindfold",
        "Arcane Monk Cloak",
        "Arcane Monk Leggings",
        "Atlantean Worm Helmet",
        "Atlantean Worm Necklace",
        "Atlantean Worm Ring",
        "Atlantean Worm Sword",
        "Chaos Staff",
        "Core Commander armor",
        "Core Commander Brigandine",
        "Core Commander Greaves",
        "Core Commander Helm",
        "Cosmic Form",
        "Glass Bead Necklace",
        "Greenhorn Pico",
        "Hydra Bone armor",
        "Hydra Bone Breastplate",
        "Hydra Bone Helm",
        "Hydra Bone Shins",
        "Ninja armor",
        "Ninja Cowl",
        "Ninja Garments",
        "Ninja Leggings",
        "Obliteration Ray",
        "Pandorium armor",
        "Pandorium Axe",
        "Pandorium Chestplate and Bracers",
        "Pandorium Helm",
        "Pandorium Pants",
        "Pinkhorn Pico",
        "Soul Medallion",
        "Splendid Deepstalker",
        "Starlight Nautilus",
        "Tome of Decay",
        "Tower Shell Necklace",
        "Trinity Heart",
        "Void Gun"
    ],
    18: [
        "Corrupted Meteor Staff",
        "Desert Guardian armor",
        "Desert Guardian Mask",
        "Desert Guardian Pants",
        "Desert Guardian Tunic",
        "Minion Detonator",
        "Riftian Lampfish",
        "Sulfossil armor",
        "Sulfossil Boots",
        "Sulfossil Cuirass",
        "Sulfossil Helmet"
    ],
    19: [
        "Stormbringer"
    ]
}
