Accessories = {
    "Other": [
        "Admin Key",
        "Azeos' Dash Feather",
        "Azeos Feather Fan",
        "Blue Leather Tome",
        "Caveling ID",
        "Core Iris",
        "Empty Crystal",
        "Glyph Parchment",
        "Golden Jellyfish",
        "Leash",
        "Lucky Coin",
        "Magic Mirror",
        "Minion Detonator",
        "Moonstone",
        "Octarine Shield",
        "Omoroth's Beak",
        "Omoroth Compass",
        "Oracle Deck",
        "Ra-Akar Automaton",
        "Rift Lens",
        "Roofing Gadget",
        "Royal Gel",
        "Rune Parchment",
        "Scorching Aegis",
        "Sentry Shield",
        "Swift Feather",
        "Thread of Fate",
        "Toxic Defender",
        "Turtle Shell",
        "Wooden Shield",
        "Worker Handcuff",
    ],
    "Necklaces": [
        "Ammonite Necklace",
        "Ancient Gem Necklace",
        "Ancient Guardian Necklace",
        "Atlantean Worm Necklace",
        "Azeos Beak Necklace",
        "Black Necklace",
        "Blob Rosary Necklace",
        "Bomb Necklace",
        "Bone Necklace",
        "Bubble Pearl Necklace",
        "Cave Guppy Necklace",
        "Conch Shell Necklace",
        "Copper Cross Necklace",
        "Coral Amulet",
        "Crescent Necklace",
        "Eostre Necklace",
        "Fang Necklace",
        "Flame Necklace",
        "Fusioned Chunk Necklace",
        "Glass Bead Necklace",
        "Gold Crystal Necklace",
        "Grub Egg Necklace",
        "Heart Berry Necklace",
        "Iron Chunk Necklace",
        "Mold Vein Necklace",
        "Neptune Necklace",
        "Nomad Necklace",
        "Oceanheart Necklace",
        "Octarine Necklace",
        "Omoroth's Necklace",
        "Pyrdra's Necklace",
        "Ra-Akar's Necklace",
        "Remedaisy Necklace",
        "Rusted Necklace",
        "Scarlet Chunk Necklace",
        "Skull Necklace",
        "Soul Medallion",
        "Torc Necklace",
        "Tower Shell Necklace",
        "Valentine Necklace",
        "Wildwarden Necklace",
    ],
    "Rings": [
        "Ancient Gem Ring",
        "Ancient Guardian Ring",
        "Atlantean Worm Ring",
        "Black Ring",
        "Bomb Ring",
        "Bone Ring",
        "Boundary Ring",
        "Caveling Mother's Ring",
        "Clot Ring",
        "Coral Ring",
        "Crescent Ring",
        "Crydra's Ring",
        "Double Ring",
        "Druidra's Ring",
        "Flame Ring",
        "Glass Bead Ring",
        "Glow Tulip Ring",
        "Golden Spike Ring",
        "Goldfish Ring",
        "Gold Crystal Ring",
        "Hourglass Ring",
        "Ivy's Ring",
        "Larva Ring",
        "Lucky Ring",
        "Magnetic Ring",
        "Melting Crystal Ring",
        "Mold Ring",
        "Morpha's Ring",
        "Noble Ring",
        "Nomad Ring",
        "Octarine Ring",
        "Omoroth's Ring",
        "Ostara Ring",
        "Petal Ring",
        "Puppet Ring",
        "Ring of Rock",
        "Ring of Sand",
        "Ring of Stone",
        "Rusted Ring",
        "Samhain Curse Ring",
        "Samhain Offering Necklace",
        "Sea Foam Ring",
        "Septum Ring",
        "Skull Ring",
        "Sky Ring",
        "Spine Ring",
        "Swift Ring",
        "Topaz Ring",
        "Valentine Ring",
        "Vicious Ring",
        "White Glass Ring",
        "Wildwarden Ring",
        "Wooden Ring",
        "Wooden Thorn Ring",
    ],
    "Bags_and_Pouches": [
        "Belt Pocket",
        "Explorer Backpack",
        "Ghorm's Stomach Bag",
        "Large Fish Pouch",
        "Large Ore and Block Pouch",
        "Large Seed and Crop Pouch",
        "Large Valuable Pouch",
        "Medium Fish Pouch",
        "Medium Ore and Block Pouch",
        "Medium Seed and Crop Pouch",
        "Medium Valuable Pouch",
        "Miner Backpack",
        "Morpha's Bubble Bag",
        "Octarine Bag",
        "Scarlet Shell Backpack",
        "Scholar Satchel",
        "Small Fish Pouch",
        "Small Ore and Block Pouch",
        "Small Seed and Crop Pouch",
        "Small Valuable Pouch",
    ],
    "Lanterns": [
        "Lantern",
        "Orb Lantern",
        "Pearl Lantern",
        "Pumpkin Lantern",
        "Small Lantern",
        "Soul Lantern",
    ],
    "Polished_Rings_and_Necklaces": [
        "Polished Copper Cross Necklace",
        "Polished Coral Amulet",
        "Polished Glow Tulip Ring",
        "Polished Golden Spike Ring",
        "Polished Gold Crystal Necklace",
        "Polished Gold Crystal Ring",
        "Polished Iron Chunk Necklace",
        "Polished Magnetic Ring",
        "Polished Octarine Necklace",
        "Polished Octarine Ring",
        "Polished Scarlet Chunk Necklace",
        "Polished Swift Ring",
    ],
}

Uncategorized = {
    "Armors": [
        "Adventurer's Hat",
        "Apprentice Hat",
        "Apprentice Pants",
        "Apprentice Robe",
        "Arcane Monk Blindfold",
        "Arcane Monk Cloak",
        "Arcane Monk Leggings",
        "Assassin Cloak",
        "Assassin Hood",
        "Atlantean Worm Helmet",
        "Blast Helmet",
        "Blast Pants",
        "Blast Plackart",
        "Blue Bikini Bottom",
        "Blue Bikini Top",
        "Blue Board Shorts",
        "Blue Party Hat",
        "Bronze Breastplate",
        "Bronze Helm",
        "Bronze Pants",
        "Carapace Breastplate",
        "Carapace Helm",
        "Caveling Chest",
        "Caveling Hood",
        "Caveling Pants",
        "Chef's Hat",
        "Chef's Jacket",
        "Chef's Pants",
        "Chicken Breast Piece",
        "Chicken Hat",
        "Chicken Pants",
        "Chieftain Headdress",
        "Chieftain Shorts",
        "Chieftain Tunic",
        "Copper Breastplate",
        "Copper Helm",
        "Copper Pants",
        "Core Commander Brigandine",
        "Core Commander Greaves",
        "Core Commander Helm",
        "Corrupt Warden Mask",
        "Corrupt Warden Shorts",
        "Corrupt Warden Tunic",
        "Cosmos Legwear",
        "Cosmos Torso",
        "Cosmos Visor Helm",
        "Cupid Tunic",
        "Desert Guardian Mask",
        "Desert Guardian Pants",
        "Desert Guardian Tunic",
        "Diving Helm",
        "Dracularva Cape",
        "Dragon Mask",
        "Eggcellent Breast Piece",
        "Eggcellent Hat",
        "Eggcellent Pants",
        "Explorer's Hat",
        "Explorer's Jacket",
        "Explorer's Pants",
        "Farmer's Hat",
        "Festive Hat",
        "Flower Crown",
        "Frankenbrute Head",
        "Galaxite Helm",
        "Galaxite Pants",
        "Galaxite Torso",
        "Gemstone Garment",
        "Gemstone Harem Pants",
        "Gingerbreadman Head",
        "Gingerbread Hood",
        "Gingerbread Pants",
        "Gingerbread Top",
        "Godsent King Breast Armor",
        "Godsent King Mask",
        "Godsent King Pants Armor",
        "Green Bikini Bottom",
        "Green Bikini Top",
        "Green Board Shorts",
        "Green Party Hat",
        "Grim Breastplate",
        "Grim Hood",
        "Grim Legwear",
        "Hazmat Helm",
        "Hazmat Suit Jacket",
        "Hazmat Suit Pants",
        "Hivebone Breastplate",
        "Hivebone Helm",
        "Hivebone Pants",
        "Hunter Cloak",
        "Hunter Hood",
        "Hydra Bone Breastplate",
        "Hydra Bone Helm",
        "Hydra Bone Shins",
        "Iron Breastplate",
        "Iron Helm",
        "Iron Pants",
        "Ivy's Pants",
        "Ivy's Thorn Harness",
        "Kelp Mantle",
        "King Slime Crown",
        "Larva Chest",
        "Larva Helm",
        "Lily Pad Hat",
        "Lily Pad Shorts",
        "Lily Pad Tunic",
        "Magma Horn Armor",
        "Magma Shin Armor",
        "Magma Torso Armor",
        "Makeshift Goggles",
        "Mercenary Headband",
        "Mercenary Pants",
        "Mercenary Tank Top",
        "Miner's Labour Suit",
        "Miner's Protective Helm",
        "Miner's Worker Pants",
        "Moldweb Breastplate",
        "Moldweb Helm",
        "Moldweb Pants",
        "Ninja Cowl",
        "Ninja Garments",
        "Ninja Leggings",
        "Octarine Breastplate",
        "Octarine Helm",
        "Octarine Pants",
        "OldRebreather",
        "Omoroth's Chestplate",
        "Omoroth's Helm",
        "Omoroth's Leg Armor",
        "Paladin Harness",
        "Paladin Mask",
        "Paladin Pants",
        "Pandorium Chestplate and Bracers",
        "Pandorium Helm",
        "Pandorium Pants",
        "Peasant Chest",
        "Peasant Hat",
        "Plague Mask",
        "Pumpkin Head",
        "Purple Party Hat",
        "Radical Rabbit Ears",
        "Radical Rabbit Headband",
        "Rain Coat",
        "Ranger Hood",
        "Ranger Pants",
        "Ranger Tunic",
        "Red Bikini Bottom",
        "Red Bikini Top",
        "Red Board Shorts",
        "Red Party Hat",
        "Researcher's Coat",
        "Researcher's Pants",
        "Rubber Boots",
        "Scarab Harness",
        "Scarab Legs",
        "Scarab Visor",
        "Scarlet Breastplate",
        "Scarlet Helm",
        "Scarlet Pants",
        "Scholar's Cloak",
        "Scholar's Hood",
        "Scuba Fins",
        "Sentry Helm",
        "Shaman Skull",
        "Shrooman Cap",
        "Skirmisher Cap",
        "Slime Armor",
        "Slime Helm",
        "Smithing Glove",
        "Snowman Hat",
        "Soaring Headgear",
        "Soaring Pants",
        "Soaring Poncho",
        "Solarite Barbute",
        "Solarite Cuirass",
        "Solarite Tassets",
        "Sorcerer Hood",
        "Sorcerer Pants",
        "Sorcerer Robe",
        "Spooky Blanket Cape",
        "Spooky Blanket Hood",
        "Stone Chestplate",
        "Stone Pants",
        "Suit Jacket",
        "Suit Pants",
        "Sulfossil Boots",
        "Sulfossil Cuirass",
        "Sulfossil Helmet",
        "Sunglasses",
        "Tassel Earrings",
        "Tassel Skirt",
        "Tassel Top",
        "Top Hat",
        "Towel",
        "Trenchcoat",
        "Wedding Dress",
        "Wildwarden Mask",
        "Wildwarden Pants",
        "Wildwarden Pauldrons",
        "Witch Doctor Hat",
        "Witch Doctor Jeans",
        "Witch Doctor Vest",
        "Wood Chest",
        "Wood Helm",
        "Wood Pants",
    ],
    "BaseBuilding": [
        "Alien Crystal Light",
        "Banner",
        "Bed",
        "Big Gold-edged Table",
        "Broken Clay Kiln",
        "Clamping Frame",
        "Coral Bridge",
        "Coral Fence",
        "Coral Fence Gate",
        "Coral Floor",
        "Drumkit",
        "Dysfunctional Coil",
        "Eerie Rug",
        "Egg Incubator",
        "Enchanted Rose",
        "Explosives Deposit",
        "Feeding Tray",
        "Festive Workbench",
        "Floor Pillow",
        "Galaxite Bridge",
        "Galaxite Fence",
        "Galaxite Fence Gate",
        "Gem-Jellyfish",
        "Geode Wall Display",
        "Glass Bridge",
        "Gold-edged Table",
        "Golden Rose Bouquet",
        "Grimy Bookshelf",
        "Ground Magma Slime",
        "Heart-shaped Rug",
        "Heart Painting",
        "Hive Larvaskin Rug",
        "Homeworld Reminiscence",
        "Large Grimy Bookshelf",
        "Large Temple Decor Rug",
        "Larvaskin Rug",
        "Larvaskin Tent",
        "Larva Skewer",
        "Lit Floor",
        "Loose Flooring",
        "Mannequin",
        "Metropolis Gate",
        "Old Smithing Bellow",
        "Paintable Floor",
        "Paintable Wall",
        "Paintable Wall",
        "Paintable Wall",
        "Paintable Wall",
        "Paintable Wall",
        "Paintable Wall",
        "Paintable Wall",
        "Paintable Wall",
        "Paintable Wall",
        "Paintable Wall",
        "Paintable Wall",
        "Paintable Wall",
        "Paintable Wall",
        "Paintable Wall",
        "Paintable Wall",
        "Pink Rose Bouquet",
        "Pocket Piano",
        "Rose Petal Flooring",
        "Rug",
        "Scarlet Bridge",
        "Scarlet Door",
        "Scarlet Fence",
        "Scarlet Fence Gate",
        "Scarlet Floor",
        "Small Clamping Frame",
        "Spear Rack",
        "Stone Bridge",
        "Stone Door",
        "Stone Fence",
        "Stone Fence Gate",
        "Stone Floor",
        "Straw-bale Wall",
        "Strolly Poly",
        "Strolly Poly Plate",
        "Temple Decor Rug",
        "Temple Pedestal",
        "Temple Throne",
        "Valentine's Candles",
        "Wall Hearts",
        "Wash Basin",
        "Water Cooler",
        "WhiteBoard",
        "White Rose Bouquet",
        "Wooden Pillar",
        "Wood Bridge",
        "Wood Door",
        "Wood Fence",
        "Wood Fence Gate",
        "Wood Floor",
        "Woven Mat",
        "Woven Straw Floor",
    ],
    "Consumables": [
        "AmberLarva2",
        "Amber Larva",
        "Anniversary Cake",
        "Arcane Potion",
        "Astral Jelly",
        "Azure Feather Fish",
        "Beached Jelly",
        "Beast Booster",
        "Beryll Angle Fish",
        "Black Steel Urchin",
        "Blue Cave Guppy",
        "Bottom Tracer",
        "Box of Chocolates",
        "Bright Lava Eater",
        "Brown Dune Tail",
        "Cake",
        "Caveling Bread",
        "Cave Coffee",
        "Cave Crunch",
        "Cereal",
        "Cheese",
        "Chewy Cone Candy",
        "CookedCakeEpic",
        "CookedCakeRare",
        "CookedCerealEpic",
        "CookedCerealRare",
        "CookedCheeseEpic",
        "CookedCheeseRare",
        "CookedDipSnackEpic",
        "CookedDipSnackRare",
        "CookedFilletEpic",
        "CookedFilletRare",
        "CookedFishBallsEpic",
        "CookedFishBallsRare",
        "CookedPanCurryEpic",
        "CookedPanCurryRare",
        "CookedPuddingEpic",
        "CookedPuddingRare",
        "CookedSaladEpic",
        "CookedSaladRare",
        "CookedSandwichEpic",
        "CookedSandwichRare",
        "CookedSmoothieEpic",
        "CookedSmoothieRare",
        "CookedSoupEpic",
        "CookedSoupRare",
        "CookedSteakEpic",
        "CookedSteakRare",
        "CookedSushiEpic",
        "CookedSushiRare",
        "CookedWrapEpic",
        "CookedWrapRare",
        "Cosmic Form",
        "Crown Squid",
        "Crystal Bone",
        "Crystal Water",
        "Curry",
        "Dagger Fin",
        "Dark Lava Eater",
        "Devil Worm",
        "Dip Snack",
        "Dip Snack",
        "Distilled Love",
        "Drape Ray",
        "Elder Dragonfish",
        "Emerald Feather Fish",
        "Enrage Potion",
        "Evil Eye Candy",
        "Expert Lure",
        "Fillet",
        "Fish Balls",
        "Food Ration",
        "Fruit Bread",
        "Gem Crab",
        "GiantMushroom2",
        "Giant Mushroom",
        "Glazed Heart Berry",
        "Glistening Deepstalker",
        "Glowing Bait",
        "Golden Chocolate",
        "Golden Dart",
        "Golden Lunacorn",
        "Golden Sunrice",
        "Greater Healing Potion",
        "Greenhorn Pico",
        "Green Bait",
        "Green Blister Head",
        "Grey Dune Tail",
        "Guardian's Potion",
        "Healing Potion",
        "Heart Berry Soda",
        "Heart of Gold",
        "Hot Chocolate",
        "Hot Punch",
        "Jasper Angle Fish",
        "Jingle Jam Cookie",
        "Keen Potion",
        "Kelp Dumpling",
        "Kizz Cola",
        "Lunacorn",
        "Lunar Cheese",
        "Marbled Meat",
        "Meadow Milk",
        "Mold Cicada",
        "Mold Cicada (Sickle)",
        "Mold Shark",
        "Mug of Coffee",
        "Mushroom",
        "Orange Cave Guppy",
        "Pact of Power Potion",
        "Paradise Fruit Basket",
        "Pet Pellet",
        "Pinkhorn Pico",
        "Pink Coralotl",
        "Pink Palace Fish",
        "Poison Aid Potion",
        "Pudding",
        "Purple Bait",
        "Rare Candy",
        "Red Bait",
        "Riftian Lampfish",
        "Roast Firepit",
        "Rock Jaw",
        "Rootbear",
        "Rose Water",
        "Rot Fish",
        "Salad",
        "Sandwich",
        "Sandy Spikeback",
        "Silver Dart",
        "Skip",
        "Slushie",
        "Smoothie",
        "Snacks Vending Machine",
        "Solid Spikeback",
        "Soup",
        "Spicy Bait",
        "Spirit Veil",
        "Splendid Amalgam",
        "Splendid Deepstalker",
        "Spooky Pop Candy",
        "Starlight Nautilus",
        "Steak",
        "Sticky Bait",
        "Stoneskin Potion",
        "Sunrice",
        "Sushi",
        "Suspended Butterfly",
        "Sweet Bait",
        "Teal Palace Fish",
        "Tentacle Jerky",
        "Tornis Kingfish",
        "Trinity Heart",
        "Triops Fossil",
        "Unusual Potion",
        "Vampire Eel",
        "Verdant Dragonfish",
        "Vit",
        "White Coralotl",
        "Winter Cookies",
        "Winter Dinner",
        "Wrap",
        "Yellow Blister Head",
    ],
    "ElectroMechanics": [
        "Boat",
        "Conveyor Belt",
        "Cross Circuit",
        "Delay Circuit",
        "Drill",
        "Dynamite Pack",
        "Easter Egg Lamp",
        "Electrical Door",
        "Electrical Wire",
        "Electricity Stick",
        "Galaxite Trap",
        "Galaxite Turret",
        "Hive Spike Trap",
        "Lamp",
        "Lever",
        "Logic Circuit",
        "Minecart",
        "Orbital Turret",
        "Poison Spike Trap",
        "Pressure Plate",
        "Pulse Circuit",
        "Rail",
        "Robot Arm",
        "Speeder",
        "Spike Trap",
        "Sprinkler",
        "Stone Turret",
        "Wooden Spike Trap",
    ],
    "Materials": [
        "Ancient Gemstone",
        "Catalyst Gemstone",
        "Channeling Gemstone",
        "Copper Bar",
        "Copper Ore",
        "Coral Wood",
        "Coral Wood Plank",
        "Crystal Grass",
        "Crystal Meteor Shard",
        "Cytoplasm",
        "Desert Ruby",
        "Energy String",
        "Fiber",
        "Fractured Limbs",
        "Fusion Alloy",
        "Galaxite Bar",
        "Galaxite Ore",
        "Gold Bar",
        "Gold Ore",
        "Iron Bar",
        "Iron Ore",
        "Jungle Emerald",
        "Large Sun Crystal",
        "Larva Meat",
        "Mechanical Part",
        "Ocean Sapphire",
        "Octarine Bar",
        "Octarine Ore",
        "Pandorium Bar",
        "Pandorium Crystal",
        "Pandorium Ore",
        "Plank",
        "Poison Slime",
        "Radiation Crystal",
        "Scarlet Bar",
        "Scarlet Ore",
        "Scrap Parts",
        "Shiny Larva Meat",
        "Slime",
        "Slippery Slime",
        "Small Pandorium Crystal",
        "Solarite Bar",
        "Solarite Ore",
        "Solarite Ore Boulder",
        "Sparkle Opal",
        "Sun Crystal",
        "Tall Crystal Grass",
        "Tin Bar",
        "Tin Ore",
        "Wood",
        "Wool",
    ],
    "MobItems": [
        "Ancient Hologram Pod",
        "Arcane Egg",
        "Arcane Symbiote",
        "Atlantean Worm Heart",
        "Bambuck",
        "Bambuck Kid",
        "BirdPoop",
        "Blasting Dung",
        "Cattle Transport Box",
        "Corrupted Sap",
        "Cracked Arcane Egg",
        "Cracked Curious Egg",
        "Cracked Fuzzy Egg",
        "Cracked Lively Egg",
        "Cracked Loyal Egg",
        "Cracked Nimble Egg",
        "Cracked Oozy Egg",
        "Cracked Oozy Lava Egg",
        "Cracked Oozy Poison Egg",
        "Cracked Oozy Royal Egg",
        "Cracked Oozy Slippery Egg",
        "Cracked Pest Egg",
        "Cracked Squishy Egg",
        "Crown Summoning Idol",
        "Curious Egg",
        "Dodo Egg",
        "Drohmble",
        "Drohmble Calf",
        "Electro-Pest",
        "Electro-Pet",
        "Embertail",
        "Fanhare",
        "Fuzzy Egg",
        "Giant Bug Brain",
        "Hardened Sap",
        "Jr. Blue Slime",
        "Jr. Lava Slime",
        "Jr. Orange Slime",
        "Jr. Purple Slime",
        "Kelple",
        "Kelple Hatchling",
        "Little Helperling",
        "Lively Egg",
        "Loyal Egg",
        "Mimite",
        "Moolin",
        "Moolin Calf",
        "Mysterious Idol",
        "Nimble Egg",
        "Offspring Capsule",
        "Oozy Egg",
        "Oozy Lava Egg",
        "Oozy Poison Egg",
        "Oozy Royal Egg",
        "Oozy Slippery Egg",
        "Owlux",
        "Pest Egg",
        "Pet Rock",
        "Pile of chum",
        "Pink Hydra Eye",
        "Prince Slime",
        "Seasonal Calendar",
        "Skull Effigy",
        "Slime Oil",
        "Squishy Egg",
        "Subterrier",
        "White Hydra Eye",
    ],
    "Nature": [
        "AbandonedCampfire",
        "Abyss Tree",
        "Amalgam Basin",
        "Amalgam Vent",
        "Amalgam Vent",
        "Ancient Feather",
        "Aquarium",
        "Azeos Lily",
        "Barnacle Grass",
        "Beach Terrarium",
        "Bicolor Coral",
        "Blackbug",
        "Blue Glowbug",
        "Broken Holoboard",
        "Broken Stone Pillar",
        "Broken Vending Machine",
        "Bush",
        "Calcified Shell",
        "Camp Matress",
        "Camp Tent",
        "Caveling Bed",
        "Caveling Chair",
        "Caveling Fireplace",
        "Caveling Floor Tile",
        "Caveling Pillar",
        "Caveling Pot",
        "Caveling Table",
        "Caveling throne",
        "Caveling Toilet",
        "Citrus Pinion",
        "Colossal Cicada Husk",
        "Cooking Pot Lid",
        "Cooking Pot Tub",
        "Core Relief Tile",
        "Crimson Coral",
        "Crimson Wing",
        "Crystal Aquarium",
        "Crystal Kelp",
        "Crystal Snail",
        "Crystal Terrarium",
        "Cyan Feather Tree",
        "Dark Caveling Floor Tile",
        "Desert Flower Vessel",
        "Desert Terrarium",
        "Dish Coral",
        "Dream Messenger",
        "Driftwood Stool",
        "Driftwood Table",
        "Dusk Fairy",
        "Earthworm",
        "Fishing Net Rack",
        "FloatyMold",
        "Flower Vessel",
        "Gem Snail",
        "Geyser",
        "Gleam Wood Seed",
        "Greenery Pod",
        "Green Glowbug",
        "Hive Bones",
        "Hive Growth",
        "Hydra Tooth",
        "Ice Wind",
        "Land Algae",
        "Large Ancient Crate",
        "Large Beached Jelly",
        "Large Bicolor Coral",
        "Large Crimson Coral",
        "Large Desert Flower Vessel",
        "Large Dish Coral",
        "Large Holoboard",
        "Large Mold Vessel",
        "Large Oasis Flower Vessel",
        "Large Poison Slime Vessel",
        "Large Slime Vessel",
        "Large Stone Shelf",
        "Larvlet",
        "Leafhopper",
        "Litho Trilobite",
        "Little Death",
        "Lucent Oak",
        "Lumen Coral",
        "Lunacorn Seed",
        "Manyleg",
        "Meadow Bush",
        "Meadow Ground",
        "Meadow Tree",
        "MoldVein",
        "Mold Pillar",
        "Mold Vessel",
        "Mold Well",
        "Moon Pincher",
        "Oasis Flower Vessel",
        "Paradise Tree",
        "Passage Aquarium",
        "Passage Terrarium",
        "Pest Bug",
        "Pink Cherry Blossom",
        "Pink Cherry Tree",
        "Potted Abyss Tree",
        "Potted Alien Flower",
        "Potted Bloom Tree",
        "Potted Cherry Tree",
        "Potted Land Algae",
        "Potted Lucent Oak",
        "Potted Lush Tree",
        "Potted Magma Tulip",
        "Potted Meadow Tree",
        "Potted Mold Pompom",
        "Potted Moonbell Tree",
        "Potted Plume Tree",
        "Potted Tree with Red Envelopes",
        "Pot Lid",
        "Pot Tub",
        "Purple Feather Tree",
        "Raided Grave",
        "Red Glowbug",
        "Rocky Aquarium",
        "Sea Shell",
        "Shadow Newt",
        "Skeleton Decor",
        "Small Bicolor Coral",
        "Small Cyan Feather Tree",
        "Small Holoboard",
        "Small Poison Slime Vessel",
        "Small Purple Feather Tree",
        "Small Slime Vessel",
        "Snoot Fly",
        "Stalagmite",
        "Stone Shelf",
        "Stone tile Cavelings",
        "Stone tile Gemstone",
        "Stone tile Scholar",
        "Sulfur Bud",
        "Sulfur Tree",
        "Sunken Aquarium",
        "Sunrice Seed",
        "Sun Kelp",
        "Sun Pincher",
        "Tall Barnacle Grass",
        "Tall Grass",
        "Tall Land Algae",
        "Tall Meadow Grass",
        "Terrarium",
        "Terra Trilobite",
        "Vending Machine",
        "Water Well",
        "White Cherry Blossom",
        "White Cherry Tree",
        "Wilderness Aquarium",
        "Wilderness Bones",
        "Wilderness Terrarium",
        "Wooden Sign Core",
        "Wooden Sign Tulip",
        "Yellow Glowbug",
    ],
    "PlaceableItems": [
        "Alien Floor Vent",
        "Alien Tech Block",
        "Alien Tech Chest",
        "Alien Tech Crate",
        "Alien Tech Floor",
        "Ancient Chest",
        "Ancient Crate",
        "Ancient Wire",
        "Arrow Sign",
        "Atlantean Worm Chest",
        "Bait Pillar",
        "Beach Block",
        "Beach Sand Ground",
        "Blue Glass Pedestal",
        "Bottled Anomaly",
        "Broken Glyph Stele",
        "Broken Quarry Timber",
        "Brute Sign",
        "Campfire",
        "Candle",
        "Candle Stack",
        "Candy Cane Wall Decoration",
        "Caveling Stool",
        "Charred Crate",
        "Charred Crate",
        "Chest",
        "Chrysalis",
        "City Floor",
        "Clay Block",
        "Clay Firing Bucket",
        "Clay Ground",
        "Clay Moss",
        "Clay Pot",
        "Coal Pit",
        "Colossal Cicada Chest",
        "Colossal Cicada Chest",
        "Copper Chest",
        "Coral Door",
        "Coral Wall",
        "Core Tech Chest",
        "Core Tech Chest",
        "Crydra Chest",
        "Crydra Chest",
        "Crystal Block",
        "Crystal Crust",
        "Crystal Ground",
        "Crystal Lamp",
        "Crystal Tent",
        "Cultist Chest",
        "Damaged Grave",
        "Dark Stone Block",
        "Dark Stone Ground",
        "Deceased Explorer",
        "Decorated Winter Tree",
        "Decorative Pot",
        "Decorative Torch",
        "Deepspace Log",
        "Desert Block",
        "Desert King Chest",
        "Desert Prince Chest",
        "Desert Queen Chest",
        "Desert Sand Ground",
        "Desert Shrub",
        "Desert Temple Block",
        "Dirt Block",
        "Dirt Ground",
        "Driftwood Wooden Crate",
        "Druidra Chest",
        "Druidra Chest",
        "Easter Egg Flowerpot",
        "Easter Garland",
        "Easter Meadow Stool",
        "Easter Meadow Table",
        "Easter Pedestal",
        "Easter Pillar",
        "Easter Workbench",
        "Eerie Chest",
        "Eerie Dresser",
        "Eerie Floor",
        "Eerie Stool",
        "Eerie Table",
        "Eerie Wall",
        "FallingRockDestructible",
        "Festive Fireplace",
        "Festive Stool",
        "Festive Table",
        "Festive Wall Lights",
        "Floating Titan's Chest",
        "Fossil Block",
        "Fossil Cluster",
        "Fungal Soil",
        "Galaxite Chest",
        "Galaxite Door",
        "Galaxite Floor",
        "Galaxite Wall",
        "Ghorm Chest",
        "Giant Left-Facing Rock Arc",
        "Giant Right-Facing Rock Arc",
        "Gingerbread House Chest",
        "Glass Floor",
        "Glass Piece",
        "Glass Wall",
        "Gleam Wood",
        "Gleam Wood Bridge",
        "Gleam Wood Door",
        "Gleam Wood Fence",
        "Gleam Wood Fence Gate",
        "Gleam Wood Floor",
        "Gleam Wood Plank",
        "Gleam Wood Wall",
        "Glurch Chest",
        "Glyph Wall",
        "Golden Ancient Chest",
        "Golden Titan's Chest",
        "Grass Block",
        "Grass Ground",
        "Gravestone",
        "Grimy Stone Floor",
        "Grimy Stone Pillar",
        "Ground Acid Slime",
        "Ground Poison Slime",
        "Ground Slime",
        "Ground Slippery Slime",
        "Haunted Hive Mother Chest",
        "Hive Mother Chest",
        "Holiday Sock Wall Decoration",
        "Igneous' Chest",
        "IndestructibleAncientWire",
        "Iron Chest",
        "Ivy's Chest",
        "Kelp Tree",
        "King Slime's Chest",
        "Laboratory Table",
        "Large Alien Tech Destructible",
        "Large Fossil Cluster",
        "Large Left-Facing Rock Arc",
        "Large Metropolis Crate",
        "Large Quarry Timber",
        "Large Right-Facing Rock Arc",
        "Large Shiny Glimmering Object",
        "Large Temple Crate",
        "Larva Hive Block",
        "Larva Hive Chest",
        "Larva Hive Ground",
        "Lava Rock",
        "Lava Rock Block",
        "Lava Rock Ground",
        "Locked Copper Chest",
        "Locked Desert King Chest",
        "Locked Desert Prince Chest",
        "Locked Desert Queen Chest",
        "Locked Galaxite Chest",
        "Locked Iron Chest",
        "Locked Octarine Chest",
        "Locked Scarlet Chest",
        "Locked Solarite Chest",
        "Lush Moss",
        "Luxury Winter Present",
        "Malugaz Chest",
        "Malugaz Chest",
        "Maze Block",
        "Maze Floor",
        "Meadow Block",
        "Metal Grate",
        "Metropolis Block",
        "Metropolis Crate",
        "Metropolis Sign",
        "Mold Block",
        "Mold Covered Chest",
        "Mold Ground",
        "Molten Wall",
        "Morpha's Chest",
        "Music Sheet Stand",
        "Oasis Block",
        "Obsidian Block",
        "Octarine Chest",
        "Office Crate",
        "Office Crate",
        "Old Wheelbarrow",
        "Overgrown Wooden Crate",
        "Paintable Festive Wall Lights",
        "Painting",
        "Pedestal",
        "Planter Box",
        "Plume Tree",
        "Poison Berry Wall",
        "Pouch Workbench",
        "Pyrdra Chest",
        "Pyrdra Chest",
        "Raided Temple Guardian Statue",
        "Rift Statue",
        "Ruins Arc",
        "Ruins Gate",
        "Ruins Pillars",
        "Ruins Tile",
        "Sandstone Rock",
        "Sand Block",
        "Sand Ground",
        "Scarlet Chest",
        "Scarlet Wall",
        "Seashell Chest",
        "Servant Grave",
        "Sign",
        "Singing Crystal",
        "Small Alien Obelisk",
        "Small Obelisk",
        "Small Sandstone Rock",
        "Smoldering Chest",
        "Snowball Pyramid",
        "Snowflake Wall Decoration",
        "Snowman",
        "Snow Block",
        "Snow Ground",
        "Solarite Chest",
        "Solarite Workbench",
        "Stone Block",
        "Stone Bricks Wall",
        "Stone Ground",
        "Stone Lantern",
        "Stone Moss",
        "Stone Pedestal",
        "Tall Alien Obelisk",
        "Tall Obelisk",
        "Temple Crate",
        "Temple Floor",
        "Temple Guardian Statue",
        "Temple Pillar",
        "Thermite Wall",
        "Thin Glass Wall",
        "Thorn Wood",
        "Tilted Grave",
        "Titan's Chest",
        "Tombstone",
        "Torch",
        "Turf Block",
        "Turf Ground",
        "Twisted Roots Torch",
        "Urban Moss",
        "Urschleims Chest",
        "Urschleims Chest",
        "Valentine's Chest",
        "Valley Moss",
        "Winter Candle Wall Decoration",
        "Winter Wreath Wall Decoration",
        "Wooden Crate",
        "Wood Stool",
        "Wood Table",
        "Wood Wall",
    ],
    "PlantsSeeds": [
        "BloatOatPlant",
        "Bloat Oat",
        "Bloat Oat Seed",
        "BombPepperPlant",
        "Bomb Pepper",
        "Bomb Pepper Seed",
        "Carrock",
        "CarrockPlant",
        "Carrock Seed",
        "CoralRootPlant",
        "Coral Wood Seed",
        "GleamRootPlant",
        "GlowingTulipPlant",
        "Glow Tulip",
        "Glow Tulip Seed",
        "Golden Bloat Oat",
        "Golden Bomb Pepper",
        "Golden Carrock",
        "Golden Glow Tulip",
        "Golden Grumpkin",
        "Golden Heart Berry",
        "Golden Pewpaya",
        "Golden Pinegrapple",
        "Golden Puffungi",
        "GrubKapokPlant",
        "Grub Kapok Seed",
        "Grumpkin",
        "GrumpkinPlant",
        "Grumpkin Seed",
        "HeartBerryPlant",
        "Heart Berry",
        "Heart Berry Seed",
        "LunacornPlant",
        "Pewpaya",
        "PewpayaPlant",
        "Pewpaya Seed",
        "Pinegrapple",
        "PinegrapplePlant",
        "Pinegrapple Seed",
        "Puffungi",
        "PuffungiPlant",
        "Puffungi Seed",
        "RootPlant",
        "Root Seed",
        "SunricePlant",
    ],
    "Seasonal": [
        "Brown Easter Egg",
        "Cookies & Milk",
        "Folding Screen",
        "Gray Easter Egg",
        "Green Easter Egg",
        "Guardian Beast Statue",
        "Large Golden Egg",
        "Love Letter",
        "Lucky Cat",
        "Mystic Knot Tassel",
        "Paper Lantern",
        "Pumpkin Coin",
        "Red Envelope",
        "Rose Easter Egg",
        "Samhain Goodie Bag",
        "Valentine's Gift",
        "Wall Paper Lantern",
        "Winter Present",
    ],
    "Special": [
        "Agartha Report",
        "Alien Fuse",
        "Ancient Coin",
        "Anomaly Report",
        "Atlantean Worm Scanner",
        "Azeos the Sky Titan Scanner",
        "Blue Glass Kalimba",
        "Broken Core Idol",
        "Broken Core Sentry",
        "Caveling Brute Plushie",
        "Chemical Ration",
        "Chipped Blade",
        "Clear Gemstone",
        "Copper Key",
        "Core Commander Summoning Idol",
        "Core Keeper - Base Theme",
        "Crydra the Ice Titan Scanner",
        "Crystal Meteor Chunk",
        "Crystal Skull Shard",
        "CSD!3! – It's Dangerous To Go Alone",
        "Daisy Flooring",
        "Druidra the Wild Titan Scanner",
        "Failed Titan",
        "Galaxite Key",
        "Ghorm's Horn",
        "Ghorm Summoning Idol",
        "Ghorm the Devourer Scanner",
        "Giant Slime Summoning Idol",
        "Glurch Eye",
        "Happy Birthday To You",
        "Haunted Hive Mother Summoning Idol",
        "Hive Mother Scanner",
        "Hive Mother Summoning Idol",
        "Igneous the Molten Mass Scanner",
        "Iron Key",
        "Ivy the Poisonous Mass Scanner",
        "Magma Slime",
        "Malugaz the Corrupted Scanner",
        "Materializer",
        "Morpha the Aquatic Mass Scanner",
        "Mysterious Doll Set",
        "Nimruza Queen of the Burrowed Sands Scanner",
        "Octarine Key",
        "Omoroth the Sea Titan Scanner",
        "Overwrite Transcript",
        "Owlboy - Main Title",
        "Primeval Slime Cell",
        "Primitive Go-kart",
        "Pyrdra the Fire Titan Scanner",
        "Ra-Akar the Sand Titan Scanner",
        "Recall Idol",
        "Renegade Go-kart",
        "Scarlet Key",
        "Shutdown Protocol",
        "Skull of the Corrupted Shaman",
        "Solarite Key",
        "Speeder Go-kart",
        "Stardew Valley - Spring (It's a Big World Outside)",
        "Stolen Crystal Heart",
        "Terraria - Journey's Beginning",
        "Urschleim Scanner",
        "Valheim - Meadows",
        "Wind Organ of Fire",
        "Wind Organ of Ice",
        "Wind Organ of Wilderness",
        "Wonky Minecart",
    ],
}

Tools_And_Weapons = {
    "Tools": [
        "Alchemist's Table",
        "Ancient Fountain",
        "Ancient Pickaxe",
        "Ancient Waypoint",
        "Anteverse Portal",
        "Automation Table",
        "Bait Workbench",
        "Basic Workbench",
        "Black Paint Brush",
        "Blue Paint Brush",
        "Boat Workbench",
        "Brown Paint Brush",
        "Bucket",
        "Bug Net",
        "Carpenter's Table",
        "Cartography Table",
        "Cello",
        "Cipher Parchment",
        "Cooking Pot",
        "Copper Anvil",
        "Copper Hoe",
        "Copper Pickaxe",
        "Copper Shovel",
        "Copper Sledge Hammer",
        "Copper Workbench",
        "Crude Drill",
        "Cyan Paint Brush",
        "Distillery Table",
        "Dresser",
        "Electricity Generator",
        "Electronics Table",
        "Flute",
        "Furnace",
        "Fury Forge",
        "Galaxite Anvil",
        "Galaxite Fishing Rod",
        "Galaxite Pickaxe",
        "Galaxite Shovel",
        "Galaxite Sledge Hammer",
        "Galaxite Workbench",
        "Garden Trowel",
        "Glass Smelter",
        "Glass Workbench",
        "Go-Kart Workbench",
        "Green Paint Brush",
        "Grey Paint Brush",
        "Grimy Table",
        "Hand Drill",
        "Harp",
        "Hydra Altar",
        "Iron Anvil",
        "Iron Fishing Rod",
        "Iron Hoe",
        "Iron Pickaxe",
        "Iron Shovel",
        "Iron Sledge Hammer",
        "Iron Workbench",
        "Jewelry Workbench",
        "Key Casting Table",
        "Large Watering Can",
        "Lava Battle Axe",
        "Livestock Workbench",
        "Loom",
        "Music Workbench",
        "Octarine Anvil",
        "Octarine Fishing Rod",
        "Octarine Garden Trowel",
        "Octarine Pickaxe",
        "Octarine Shovel",
        "Octarine Sledge Hammer",
        "Octarine Workbench",
        "Orange Paint Brush",
        "Painter's Table",
        "Peach Paint Brush",
        "Pickaxe Head",
        "Pink Paint Brush",
        "Portal",
        "Proficient Jewelry Workbench",
        "Purple Paint Brush",
        "Railway Forge",
        "Red Paint Brush",
        "Salvage and Repair Station",
        "Samhain Workbench",
        "Scarlet Anvil",
        "Scarlet Fishing Rod",
        "Scarlet Hand Drill",
        "Scarlet Hoe",
        "Scarlet Pickaxe",
        "Scarlet Shovel",
        "Scarlet Sledge Hammer",
        "Scarlet Workbench",
        "Smelter Kiln",
        "Solarite Anvil",
        "Solarite Fishing Rod",
        "Solarite Pickaxe",
        "Soul Seeker",
        "Table Saw",
        "Teal Paint Brush",
        "Thumper",
        "Tin Anvil",
        "Tin Fishing Rod",
        "Tin Hoe",
        "Tin Pickaxe",
        "Tin Shovel",
        "Tin Sledge Hammer",
        "Tin Workbench",
        "Upgrade Station",
        "Valentine Crafting Table",
        "Watering Can",
        "White Paint Brush",
        "Wooden Hoe",
        "Wooden Sword",
        "Wood Fishing Rod",
        "Wood Pickaxe",
        "Wood Shovel",
        "Yellow Paint Brush",
    ],
    "Weapons": [
        "Anchor Axe",
        "Arcane Staff",
        "Atlantean Worm Sword",
        "BatMinion",
        "Battle Axe",
        "Blowpipe",
        "Blue Firework Rocket",
        "Bomb",
        "Bomb Scarab Mortar",
        "Broken Handle",
        "Bubble Gun",
        "Burnzooka",
        "Chaos Staff",
        "Concealed Blade",
        "Copper Sword",
        "Corrupted Meteor Staff",
        "Crude Bomb",
        "Crystal Shard Club",
        "Cupid Bow",
        "Fireball Staff",
        "FireMiteMinion",
        "Flintlock Musket",
        "Galaxite Chakram",
        "Galaxite Dagger",
        "Galaxite Sword",
        "Green Firework Rocket",
        "Grubzooka",
        "Hand Mortar",
        "Hunting Spear",
        "Hydra Bone Shield",
        "Hydra Bone Sword",
        "Iron Bow",
        "Iron Halberd",
        "Iron Shield",
        "Iron Sword",
        "Large Bomb",
        "Larva Spike Club",
        "MeleeMinion",
        "Obliteration Ray",
        "Octarine Axe",
        "Octarine Bow",
        "Octarine Sword",
        "OrbitingMinion",
        "Pandorium Axe",
        "Phantom Spark",
        "Pipe Club",
        "PoisonMinion",
        "Poisonous Sickle",
        "Prehistoric Crystal Spear",
        "Purple Firework Rocket",
        "Quill Rifle",
        "RadiatingMinion",
        "Red Firework Rocket",
        "Ricochet Shuriken",
        "Ritual Dagger",
        "Rune Song",
        "Rusty Dagger",
        "Scarlet Crossbow",
        "Scarlet Dagger",
        "Scarlet Sword",
        "Scholar's Staff",
        "Simple Staff",
        "Slime Sword",
        "Slingshot",
        "Slippery Slime Sword",
        "Snowball",
        "Solarite Crossbow",
        "Solarite Sword",
        "Sticky Stick",
        "Stormbringer",
        "Sulfur Bomb",
        "Sun Caller",
        "Tentacle Whip",
        "The BIG",
        "Throwing Daggers",
        "Tin Axe",
        "Tin Dagger",
        "Tin Sword",
        "Tome of Ashes",
        "Tome of Decay",
        "Tome of Pestilence",
        "Tome of the Dark",
        "Tome of the Dead",
        "Tome of the Deep",
        "Void Gun",
        "Wood Bow",
        "Wood Crossbow",
        "Yellow Firework Rocket",
        "Zealot's Scimitar",
    ],
}

Valuables = {
    "Figurines": [
        "Acid Larva Figurine",
        "Atlantean Worm Figurine",
        "Awakened Azeos Figurine",
        "Azeos Figurine",
        "Bakery Brute Figurine",
        "Big Dracularva Figurine",
        "Big Hive Larva Figurine",
        "Big Larva Figurine",
        "Blue Slime Figurine",
        "Bomb Scarab Figurine",
        "Bubble Crab Figurine",
        "Carrot Slime Figurine",
        "Caveling Assassin Figurine",
        "Caveling Brute Figurine",
        "Caveling Figurine",
        "Caveling Gardener Figurine",
        "Caveling Hunter Figurine",
        "Caveling Mummy Figurine",
        "Caveling Scholar Figurine",
        "Caveling Shaman Figurine",
        "Caveling Skirmisher Figurine",
        "Caveling Spearman Figurine",
        "Cicada Nymph Figurine",
        "Clay Burrower Figurine",
        "Cocoon Figurine",
        "Colossal Amoeba Figurine",
        "Core Commander Figurine",
        "Core Figurine",
        "Core Sentry Figurine",
        "Crydra Figurine",
        "Druidra Figurine",
        "Electro-Pest Figurine",
        "Floracada Figurine",
        "Frankenbrute Figurine",
        "Ghorm Figurine",
        "Gingerbreadling Figurine",
        "Glurch Figurine",
        "Gold Scarab Figurine",
        "Haunted Hive Mother Figurine",
        "Hive Larva Figurine",
        "Hive Mother Figurine",
        "Igneous Figurine",
        "Infected Caveling Figurine",
        "Ivy Figurine",
        "King Slime Figurine",
        "Larva Figurine",
        "Lava Butterfly Figurine",
        "Lava Slime Figurine",
        "Malugaz Figurine",
        "Mimite Figurine",
        "Mold Tentacle Figurine",
        "Morpha Figurine",
        "Nilipede Figurine",
        "Nimruza Figurine",
        "Omoroth Figurine",
        "Orbital Turret Figurine",
        "Pumpking Caveling Figurine",
        "Purple Slime Figurine",
        "Pyrdra Figurine",
        "Ra-Akar Figurine",
        "Red Slime Figurine",
        "Santa Shrooman Figurine",
        "Shrooman Brute Figurine",
        "Shrooman Figurine",
        "Slime Figurine",
        "Snare Plant Figurine",
        "Snowhead Slime Figurine",
        "Spookaveling Figurine",
        "Starwand Shaman Figurine",
        "Sulfur Worm Figurine",
        "Tentacle Figurine",
        "Unleashed Core Commander Figurine",
        "Urschleim Figurine",
    ],
    "Valuables": [
        "Adder Stone",
        "Amber Chunk",
        "Amber Fish Egg",
        "Ammonite",
        "Ancient Fishing Hook",
        "Ancient Gem Plate",
        "Ancient Golden Coin",
        "Ancient Makeup Set",
        "Antique Board Game",
        "Azeos Urn",
        "Bag of Marbles",
        "Balloon Spore",
        "Bent Fork",
        "Black Bubble Pearl",
        "Black Desert Diamond",
        "Blood Skull",
        "Blue Glass Shard",
        "Blue Kelp",
        "Bone Creole",
        "Brave Merchant",
        "Broken Core Idol",
        "Broken Gourd",
        "Broken Toy Ship",
        "Bubble Pearl",
        "Caveling Cup",
        "Caveling Doll",
        "Caveling Effigy",
        "Caveling Medal",
        "Caveling Perfume",
        "Caveling Prophet Mask",
        "Caveling Sandal",
        "Caveling Skull",
        "Ceremonial Flute",
        "Charred Caveling Skull",
        "Chipped Plate",
        "Crystal Spearhead",
        "Crystal Sphere",
        "Crystal Star",
        "Dark Blue Kelp",
        "Data Slate",
        "Desert Diamond",
        "Dry Butterfly",
        "Early Human Skull",
        "Ear Plate",
        "Enhydro Crystal",
        "Feather Fish Scale",
        "Fish Fossil",
        "Fizzy Crystal",
        "Flesh Kelp",
        "Forked Coral",
        "Frozen Flame",
        "Fungal Bone",
        "Geode",
        "Giant Germ",
        "Giant Mite",
        "Giant Squid Eye",
        "Golden Caveling Mask",
        "Golden Cocoon",
        "Golden Feather",
        "Golden Needle",
        "Golden Starfish",
        "Golden Whistle",
        "Green Kelp",
        "Grey Kelp",
        "Grub Knot",
        "Grub Pearl",
        "Hard Thorn",
        "Incense Bowl",
        "Kingfish Scale",
        "Leaf Fossil",
        "Lost Paddle",
        "Lump of Coal",
        "Luxurious Handmirror",
        "Mechanical Arm",
        "Melting Lava Wing",
        "Mildew Leaf",
        "Mold Dew",
        "Mold Shell",
        "Mucus Amoeba",
        "Music Bowl",
        "Nilipede",
        "Nuclear Battery",
        "Ocarina",
        "Old Amulet",
        "Old Journal",
        "Old Spore Mask",
        "Omoroth Urn",
        "Opabinia Fossil",
        "Pale Kelp",
        "Parasite Fossil",
        "Petrified Coral",
        "Petrified Egg",
        "Petrified Trilobite",
        "Playing Dice",
        "Plume Ball",
        "Polished Shell",
        "Precious Urn",
        "Processor Chip",
        "Ra-Akar Urn",
        "Rainbow Kelp",
        "Red Kelp",
        "Ritual Goblet",
        "Rusty Fishing Hook",
        "Rusty Spoon",
        "Scarab Wingcover",
        "Screen Device",
        "Sealed Beverage",
        "Seismic Clock",
        "Sentry Nutcracker",
        "Shark Tooth",
        "Small Caveling Skull",
        "Snow Globe",
        "Soft Sponge",
        "Starlight Shards",
        "Stone Cap",
        "Timeless Hourglass",
        "Triangle Trinket",
        "Twisted Agate",
        "Void Neuron",
        "White Whistle",
        "Winter Bell",
        "Yellow Kelp",
    ],
    "Oracle_Cards": [
        "Oracle Card Aura",
        "Oracle Card Brilliance",
        "Oracle Card Endurance",
        "Oracle Card Entity",
        "Oracle Card Inspiration",
        "Oracle Card Metropolis",
        "Oracle Card Radiance",
        "Oracle Card Temperance",
        "Oracle Card Wisdom",
    ],
}

