# Inageme name
# Updated manually

LOOT_ITEMS = {
    "Wildwarden Mask",
    "Wildwarden Pauldrons",
    "Wildwarden Pants",
    "Adventurer's Hat",
    "Apprentice Hat",
    "Apprentice Robe",
    "Apprentice Pants",
    "Arcane Monk Blindfold",
    "Arcane Monk Cloak", 
    "Arcane Monk Leggings",
    "Assassin Hood",
    "Assassin Cloak",
    "Blast Helmet",
    "Blast Plackart",
    "Blast Pants",
    "Blue Bikini Bottom",
    "Blue Bikini Top",
    "Blue Board Shorts",
    "Carapace Helm",
    "Carapace Breastplate",
    "Carapace Helm",
    "Carapace Breastplate",
    "Caveling Hood",
    "Caveling Chest",
    "Caveling Pants",
    "Chieftain Headdress",
    "Chieftain Tunic",
    "Chieftain Shorts",
    "Corrupt Warden Mask",
    "Corrupt Warden Tunic",
    "Corrupt Warden Shorts",
    "Cosmos Visor Helm",
    "Cosmos Torso",
    "Cosmos Legwear",
    "Desert Guardian Mask",
    "Desert Guardian Tunic", 
    "Desert Guardian Pants",
    "Paladin Mask",
    "Paladin Harness",
    "Paladin Pants",
    }
