MERCHANT_ITEMS = {
    "Anniversary Cake",
    "Ancient Gemstone",
    "Azure Feather Fish",
    "Bait Pillar",
    "Blue Party Hat",
    "Cave Coffee",
    "Cave Crunch",
    "Caveling Bread",
    "Copper Ore",
    "Core Commander Summoning Idol",
    "Core Figurine",
    "Crystal Water",
    "Curious Egg",
    "Dagger Fin",
    "Distillery Table",
    "Dragon Mask",
    "Easter Workbench",
    "Eerie Chest",
    "Empty Crystal",
    "Fiber",
    "Festive Workbench",
    "Folding Screen",
    "Geode Wall Display",
    "Ghorm Summoning Idol",
    "Giant Slime Summoning Idol",
    "Gingerbread House Chest",
    "Glazed Heart Berry",
    "Gold Ore",
    "Goldfish Ring",
    "Gray Easter Egg",
    "Green Bait",
    "Green Easter Egg",
    "Green Party Hat",
    "Guardian Beast Statue",
    "Happy Birthday To You",
    "Hazmat Helm",
    "Hazmat Suit Jacket",
    "Hazmat Suit Pants",
    "Heart Berry Soda",
    "Hive Mother Summoning Idol",
    "Iron Ore",
    "Large Golden Egg",
    "Little Helperling",
    "Lucky Cat",
    "Lucky Ring",
    "Lunar Cheese",
    "Mechanical Part",
    "Mystic Knot Tassel",
    "Neptune Necklace",
    "Oracle Card Metropolis",
    "Orange Cave Guppy",
    "Paper Lantern",
    "Potted Tree with Red Envelopes",
    "Pouch Workbench",
    "Purple Bait",
    "Purple Party Hat",
    "Red Bait",
    "Red Party Hat",
    "Rose Easter Egg",
    "Rune Parchment",
    "Samhain Workbench",
    "Scrap Parts",
    "Sea Foam Ring",
    "Skeleton Decor",
    "Tentacle Jerky",
    "Tin Ore",
    "Unusual Potion",
    "Valentine Crafting Table",
    "Valentine's Chest",
    "Valentine's Gift",
    "Wall Paper Lantern"
}