# "Asset name" : "Ingame name"
# Updated manually

NAME_OVERRIDES = {
    "Eggcellent Suit": "Eggcellent Breast Piece",
    "Chicken Suit": "Chicken Breast Piece",
    "Santa Helm": "Festive Hat",
    "Snowman Helm": "Snowman Hat",
    "Gingerbread Breast Armor": "Gingerbread Hood",
    "Gingerbread Hood Helm": "Gingerbread Top",
    "Gingerbread Pants Armor": "Gingerbread Pants",
    "Gingerbread Man Helm": "Gingerbreadman Head",
    "Radical Rabbit Ears Diadem": "Radical Rabbit Headband",
    "Scarab Breast": "Scarab Harness",  
    "Scarab Helm": "Scarab Legs",  
    "Scarab Pants Armor": "Scarab Visor",  
    "Ivy's Thorn Harness": "Ivy's Chest",
    "Ghost Blanket Helm": "Spooky Blanket Hood",
    "Ghost Blanket Breast Armor": "Spooky Blanket Cape",
    "Vampire Cape Breast Armor": "Dracularva Cape",
    "Pandorium Chestplateand Bracers": "Pandorium Chestplate and Bracers",
    "Frankenstein Helm": "Frankenbrute Head",
    "Lava Helm": "Magma Horn Armor",
    "Lava Breast Armor": "Magma Torso Armor",
    "Lava Pants Armor": "Magma Shin Armor",
    "Chefs Hat" : "Chef's Hat",
    "Chefs Jacket" : "Chef's Jacket",
    "Chefs Pants" : "Chef's Pants",
    "Assassin Helm": "Assassin Hood",
    "Assassin Breast Armor": "Assassin Cloak",
    "Desert Breast Armor": "Paladin Harness",
    "Desert Helm": "Paladin Mask",
    "Desert Pants Armor": "Paladin Pants",
    "Tomeof Ashes" : "Tome of Ashes",
    "Tomeof Decay": "Tome of Decay",
    "Tomeof Pestilence": "Tome of Pestilence",
    "Tomeofthe Dark" : "Tome of the Dark",
    "Tomeofthe Deep" : "Tome of the Deep",
    "Tomeofthe Dead": "Tome of the Dead",
    "Zealots Scimitar": "Zealot's Scimitar",
}