# Inageme name
# Updated manually

SEASONAL_ITEMS = {
    "Chicken Hat",
    "Chicken Breast Piece",
    "Chicken Pants",
    "Eggcellent Hat",
    "Eggcellent Breast Piece",
    "Eggcellent Pants",
    "Easter Egg Lamp",
    "Easter Garland",
    "Daisy Flooring",
    "Easter Egg Flowerpot",
    "Easter Pillar",
    "Easter Meadow Stool",
    "Easter Meadow Table",
    "Easter Pedestal",
    "Radical Rabbit Ears",
    "Radical Rabbit Headband",
    "Eostre Necklace",
    "Ostara Ring",
    "Awakened Azeos Figurine",
    "Golden Titan's Chest",
    "Fruit Bread",
    "Hot Chocolate",
    "Winter Cookies",
    "Winter Wreath Wall Decoration",
    "Holiday Sock Wall Decoration",
    "Candy Cane Wall Decoration",
    "Winter Candle Wall Decoration",
    "Snowflake Wall Decoration",
    "Crystal Star",
    "Snow Globe",
    "Lump of Coal",
    "Snowman Hat",
    "Festive Hat",
    "Hot Punch",
    "Winter Dinner",
    "Golden Chocolate",
    "Crystal Star",
    "Winter Bell",
    "Sentry Nutcracker",
    "Red Firework Rocket",
    "Green Firework Rocket",
    "Blue Firework Rocket",
    "Yellow Firework Rocket",
    "Purple Firework Rocket",
    "The BIG",
    "Starwand Shaman Figurine",
    "Snowhead Slime Figurine",
    "Carrot Slime Figurine",
    "Bakery Brute Figurine",
    "Gingerbreadling Figurine",
    "Santa Shrooman Figurine",
    "Gingerbreadman Head",
    "Gingerbread Hood",
    "Gingerbread Top",
    "Gingerbread Pants",
    "Rose Petal Flooring",  
    "Pink Rose Bouquet",  
    "White Rose Bouquet",  
    "Rose Water",  
    "Box of Chocolates",  
    "Cupid Bow",  
    "Valentine Necklace",  
    "Valentine Ring",  
    "Distilled Love",  
    "Cupid Tunic",  
    "Enchanted Rose",  
    "Golden Rose Bouquet",  
    "Heart of Gold",
    "Chewy Cone Candy",
    "Spooky Pop Candy",
    "Evil Eye Candy",
    "Grumpkin Seed",
    "Pumpkin Lantern",
    "Spooky Blanket Hood",
    "Spooky Blanket Cape",
    "Pumpkin Head",
    "Frankenbrute Head",
    "Dracularva Cape",
    "Haunted Hive Mother Summoning Idol",
    "Green Party Hat",
    "Red Party Hat",
    "Blue Party Hat",
    "Purple Party Hat",
    "Dragon Mask"
}
