# Inageme name
# Updated manually

SEASONAL_ITEMS = {
    "Awakened Azeos Figurine",
    "Bakery Brute Figurine",
    "Big Dracularva Figurine",
    "Blue Firework Rocket",
    "Blue Party Hat",
    "Box of Chocolates",
    "Candle Stack",
    "Candy Cane Wall Decoration",
    "Carrot Slime Figurine",
    "Chewy Cone Candy",
    "Chicken Breast Piece",
    "Chicken Hat",
    "Chicken Pants",
    "Cookies & Milk",
    "Crystal Star",
    "Cupid Bow",
    "Cupid Tunic",
    "Daisy Flooring",
    "Distilled Love",
    "Dracularva Cape",
    "Dragon Mask",
    "Easter Egg Flowerpot",
    "Easter Egg Lamp",
    "Easter Garland",
    "Easter Meadow Stool",
    "Easter Meadow Table",
    "Easter Pedestal",
    "Easter Pillar",
    "Eerie Dresser",
    "Eerie Floor",
    "Eerie Rug",
    "Eerie Stool",
    "Eerie Table",
    "Eerie Wall",
    "Eggcellent Breast Piece",
    "Eggcellent Hat",
    "Eggcellent Pants",
    "Enchanted Rose",
    "Evil Eye Candy",
    "Festive Hat",
    "Festive Workbench",
    "Frankenbrute Figurine",
    "Frankenbrute Head",
    "Fruit Bread",
    "Gingerbread Armor",
    "Gingerbread Hood",
    "Gingerbread House Chest",
    "Gingerbread Top",
    "Gingerbread Pants",
    "Gingerbreadling Figurine",
    "Gingerbreadman Head",
    "Golden Chocolate",
    "Golden Rose Bouquet",
    "Golden Titan's Chest",
    "Green Firework Rocket",
    "Green Party Hat",
    "Grumpkin Seed",
    "Haunted Hive Mother Summoning Idol",
    "Heart of Gold",
    "Holiday Sock Wall Decoration",
    "Hot Chocolate",
    "Hot Punch",
    "Little Helperling",
    "Lump of Coal",
    "Ostara Ring",
    "Pink Rose Bouquet",
    "Pumpkin Head",
    "Pumpkin Lantern",
    "Pumpking Caveling Figurine",
    "Purple Firework Rocket",
    "Purple Party Hat",
    "Radical Rabbit Ears",
    "Radical Rabbit Headband",
    "Red Firework Rocket",
    "Red Party Hat",
    "Rose Petal Flooring",
    "Rose Water",
    "Samhain Goodie Bag",
    "Santa Shrooman Figurine",
    "Sentry Nutcracker",
    "Snow Globe",
    "Snowball",
    "Snowflake Wall Decoration",
    "Snowhead Slime Figurine",
    "Snowman Hat",
    "Spookaveling Figurine",
    "Spooky Blanket Armor",
    "Spooky Blanket Cape",
    "Spooky Blanket Hood",
    "Spooky Pop Candy",
    "Starwand Shaman Figurine",
    "The BIG",
    "Twisted Roots Torch",
    "Valentine Necklace",
    "Valentine Ring",
    "White Rose Bouquet",
    "Winter Bell",
    "Winter Candle Wall Decoration",
    "Winter Cookies",
    "Winter Dinner",
    "Winter Wreath Wall Decoration",
    "Yellow Firework Rocket"
}
